// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRefresher creates a new instance of MockRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefresher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRefresher is an autogenerated mock type for the Refresher type
type MockRefresher struct {
	mock.Mock
}

type MockRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefresher) EXPECT() *MockRefresher_Expecter {
	return &MockRefresher_Expecter{mock: &_m.Mock}
}

// RefreshAll provides a mock function for the type MockRefresher
func (_mock *MockRefresher) RefreshAll(ctx context.Context, kind string, libraryPath string) error {
	ret := _mock.Called(ctx, kind, libraryPath)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, kind, libraryPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefresher_RefreshAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAll'
type MockRefresher_RefreshAll_Call struct {
	*mock.Call
}

// RefreshAll is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - libraryPath string
func (_e *MockRefresher_Expecter) RefreshAll(ctx any, kind any, libraryPath any) *MockRefresher_RefreshAll_Call {
	return &MockRefresher_RefreshAll_Call{Call: _e.mock.On("RefreshAll", ctx, kind, libraryPath)}
}

func (_c *MockRefresher_RefreshAll_Call) Run(run func(ctx context.Context, kind string, libraryPath string)) *MockRefresher_RefreshAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRefresher_RefreshAll_Call) Return(err error) *MockRefresher_RefreshAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefresher_RefreshAll_Call) RunAndReturn(run func(ctx context.Context, kind string, libraryPath string) error) *MockRefresher_RefreshAll_Call {
	_c.Call.Return(run)
	return _c
}
