// Code generated by ent, DO NOT EDIT.

package episode

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the episode type in the database.
	Label = "episode"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldOverview holds the string denoting the overview field in the database.
	FieldOverview = "overview"
	// FieldAirDate holds the string denoting the air_date field in the database.
	FieldAirDate = "air_date"
	// FieldMonitored holds the string denoting the monitored field in the database.
	FieldMonitored = "monitored"
	// FieldAbsoluteNumber holds the string denoting the absolute_number field in the database.
	FieldAbsoluteNumber = "absolute_number"
	// FieldGrabFailures holds the string denoting the grab_failures field in the database.
	FieldGrabFailures = "grab_failures"
	// FieldLastSearchAt holds the string denoting the last_search_at field in the database.
	FieldLastSearchAt = "last_search_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeSeason holds the string denoting the season edge name in mutations.
	EdgeSeason = "season"
	// EdgeDownloadRecords holds the string denoting the download_records edge name in mutations.
	EdgeDownloadRecords = "download_records"
	// EdgeAnchoredDownloadRecords holds the string denoting the anchored_download_records edge name in mutations.
	EdgeAnchoredDownloadRecords = "anchored_download_records"
	// EdgeMediaFiles holds the string denoting the media_files edge name in mutations.
	EdgeMediaFiles = "media_files"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the episode in the database.
	Table = "episodes"
	// SeasonTable is the table that holds the season relation/edge.
	SeasonTable = "episodes"
	// SeasonInverseTable is the table name for the Season entity.
	// It exists in this package in order to avoid circular dependency with the "season" package.
	SeasonInverseTable = "seasons"
	// SeasonColumn is the table column denoting the season relation/edge.
	SeasonColumn = "season_episodes"
	// DownloadRecordsTable is the table that holds the download_records relation/edge. The primary key declared below.
	DownloadRecordsTable = "download_record_episodes"
	// DownloadRecordsInverseTable is the table name for the DownloadRecord entity.
	// It exists in this package in order to avoid circular dependency with the "downloadrecord" package.
	DownloadRecordsInverseTable = "download_records"
	// AnchoredDownloadRecordsTable is the table that holds the anchored_download_records relation/edge.
	AnchoredDownloadRecordsTable = "download_records"
	// AnchoredDownloadRecordsInverseTable is the table name for the DownloadRecord entity.
	// It exists in this package in order to avoid circular dependency with the "downloadrecord" package.
	AnchoredDownloadRecordsInverseTable = "download_records"
	// AnchoredDownloadRecordsColumn is the table column denoting the anchored_download_records relation/edge.
	AnchoredDownloadRecordsColumn = "episode_download_records"
	// MediaFilesTable is the table that holds the media_files relation/edge.
	MediaFilesTable = "media_files"
	// MediaFilesInverseTable is the table name for the MediaFile entity.
	// It exists in this package in order to avoid circular dependency with the "mediafile" package.
	MediaFilesInverseTable = "media_files"
	// MediaFilesColumn is the table column denoting the media_files relation/edge.
	MediaFilesColumn = "episode_media_files"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "media_events"
	// EventsInverseTable is the table name for the MediaEvent entity.
	// It exists in this package in order to avoid circular dependency with the "mediaevent" package.
	EventsInverseTable = "media_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "episode_events"
)

// Columns holds all SQL columns for episode fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldNumber,
	FieldTitle,
	FieldOverview,
	FieldAirDate,
	FieldMonitored,
	FieldAbsoluteNumber,
	FieldGrabFailures,
	FieldLastSearchAt,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "episodes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"season_episodes",
}

var (
	// DownloadRecordsPrimaryKey and DownloadRecordsColumn2 are the table columns denoting the
	// primary key for the download_records relation (M2M).
	DownloadRecordsPrimaryKey = []string{"episode_id", "download_record_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultMonitored holds the default value on creation for the "monitored" field.
	DefaultMonitored bool
	// DefaultAbsoluteNumber holds the default value on creation for the "absolute_number" field.
	DefaultAbsoluteNumber uint16
	// DefaultGrabFailures holds the default value on creation for the "grab_failures" field.
	DefaultGrabFailures uint8
)

// Status defines the type for the "status" enum field.
type Status string

// StatusWanted is the default value of the Status enum.
const DefaultStatus = StatusWanted

// Status values.
const (
	StatusWanted      Status = "wanted"
	StatusDownloading Status = "downloading"
	StatusImporting   Status = "importing"
	StatusPaused      Status = "paused"
	StatusAvailable   Status = "available"
	StatusSkipped     Status = "skipped"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusWanted, StatusDownloading, StatusImporting, StatusPaused, StatusAvailable, StatusSkipped:
		return nil
	default:
		return fmt.Errorf("episode: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Episode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByOverview orders the results by the overview field.
func ByOverview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverview, opts...).ToFunc()
}

// ByAirDate orders the results by the air_date field.
func ByAirDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAirDate, opts...).ToFunc()
}

// ByMonitored orders the results by the monitored field.
func ByMonitored(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitored, opts...).ToFunc()
}

// ByAbsoluteNumber orders the results by the absolute_number field.
func ByAbsoluteNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbsoluteNumber, opts...).ToFunc()
}

// ByGrabFailures orders the results by the grab_failures field.
func ByGrabFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrabFailures, opts...).ToFunc()
}

// ByLastSearchAt orders the results by the last_search_at field.
func ByLastSearchAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSearchAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySeasonField orders the results by season field.
func BySeasonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeasonStep(), sql.OrderByField(field, opts...))
	}
}

// ByDownloadRecordsCount orders the results by download_records count.
func ByDownloadRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDownloadRecordsStep(), opts...)
	}
}

// ByDownloadRecords orders the results by download_records terms.
func ByDownloadRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownloadRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnchoredDownloadRecordsCount orders the results by anchored_download_records count.
func ByAnchoredDownloadRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnchoredDownloadRecordsStep(), opts...)
	}
}

// ByAnchoredDownloadRecords orders the results by anchored_download_records terms.
func ByAnchoredDownloadRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnchoredDownloadRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMediaFilesCount orders the results by media_files count.
func ByMediaFilesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMediaFilesStep(), opts...)
	}
}

// ByMediaFiles orders the results by media_files terms.
func ByMediaFiles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaFilesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSeasonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeasonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeasonTable, SeasonColumn),
	)
}
func newDownloadRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownloadRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DownloadRecordsTable, DownloadRecordsPrimaryKey...),
	)
}
func newAnchoredDownloadRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnchoredDownloadRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnchoredDownloadRecordsTable, AnchoredDownloadRecordsColumn),
	)
}
func newMediaFilesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaFilesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MediaFilesTable, MediaFilesColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
