// Code generated by ent, DO NOT EDIT.

package episode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datahearth/streamline/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUpdateTime, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldNumber, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldTitle, v))
}

// Overview applies equality check predicate on the "overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldOverview, v))
}

// AirDate applies equality check predicate on the "air_date" field. It's identical to AirDateEQ.
func AirDate(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldAirDate, v))
}

// Monitored applies equality check predicate on the "monitored" field. It's identical to MonitoredEQ.
func Monitored(v bool) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldMonitored, v))
}

// AbsoluteNumber applies equality check predicate on the "absolute_number" field. It's identical to AbsoluteNumberEQ.
func AbsoluteNumber(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldAbsoluteNumber, v))
}

// GrabFailures applies equality check predicate on the "grab_failures" field. It's identical to GrabFailuresEQ.
func GrabFailures(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldGrabFailures, v))
}

// LastSearchAt applies equality check predicate on the "last_search_at" field. It's identical to LastSearchAtEQ.
func LastSearchAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldLastSearchAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldUpdateTime, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...uint16) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...uint16) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldNumber, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContainsFold(FieldTitle, v))
}

// OverviewEQ applies the EQ predicate on the "overview" field.
func OverviewEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "overview" field.
func OverviewNEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "overview" field.
func OverviewIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "overview" field.
func OverviewNotIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "overview" field.
func OverviewGT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "overview" field.
func OverviewGTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "overview" field.
func OverviewLT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "overview" field.
func OverviewLTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "overview" field.
func OverviewContains(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "overview" field.
func OverviewHasPrefix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "overview" field.
func OverviewHasSuffix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewIsNil applies the IsNil predicate on the "overview" field.
func OverviewIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldOverview))
}

// OverviewNotNil applies the NotNil predicate on the "overview" field.
func OverviewNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldOverview))
}

// OverviewEqualFold applies the EqualFold predicate on the "overview" field.
func OverviewEqualFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "overview" field.
func OverviewContainsFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContainsFold(FieldOverview, v))
}

// AirDateEQ applies the EQ predicate on the "air_date" field.
func AirDateEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldAirDate, v))
}

// AirDateNEQ applies the NEQ predicate on the "air_date" field.
func AirDateNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldAirDate, v))
}

// AirDateIn applies the In predicate on the "air_date" field.
func AirDateIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldAirDate, vs...))
}

// AirDateNotIn applies the NotIn predicate on the "air_date" field.
func AirDateNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldAirDate, vs...))
}

// AirDateGT applies the GT predicate on the "air_date" field.
func AirDateGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldAirDate, v))
}

// AirDateGTE applies the GTE predicate on the "air_date" field.
func AirDateGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldAirDate, v))
}

// AirDateLT applies the LT predicate on the "air_date" field.
func AirDateLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldAirDate, v))
}

// AirDateLTE applies the LTE predicate on the "air_date" field.
func AirDateLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldAirDate, v))
}

// AirDateIsNil applies the IsNil predicate on the "air_date" field.
func AirDateIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldAirDate))
}

// AirDateNotNil applies the NotNil predicate on the "air_date" field.
func AirDateNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldAirDate))
}

// MonitoredEQ applies the EQ predicate on the "monitored" field.
func MonitoredEQ(v bool) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldMonitored, v))
}

// MonitoredNEQ applies the NEQ predicate on the "monitored" field.
func MonitoredNEQ(v bool) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldMonitored, v))
}

// AbsoluteNumberEQ applies the EQ predicate on the "absolute_number" field.
func AbsoluteNumberEQ(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldAbsoluteNumber, v))
}

// AbsoluteNumberNEQ applies the NEQ predicate on the "absolute_number" field.
func AbsoluteNumberNEQ(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldAbsoluteNumber, v))
}

// AbsoluteNumberIn applies the In predicate on the "absolute_number" field.
func AbsoluteNumberIn(vs ...uint16) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldAbsoluteNumber, vs...))
}

// AbsoluteNumberNotIn applies the NotIn predicate on the "absolute_number" field.
func AbsoluteNumberNotIn(vs ...uint16) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldAbsoluteNumber, vs...))
}

// AbsoluteNumberGT applies the GT predicate on the "absolute_number" field.
func AbsoluteNumberGT(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldAbsoluteNumber, v))
}

// AbsoluteNumberGTE applies the GTE predicate on the "absolute_number" field.
func AbsoluteNumberGTE(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldAbsoluteNumber, v))
}

// AbsoluteNumberLT applies the LT predicate on the "absolute_number" field.
func AbsoluteNumberLT(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldAbsoluteNumber, v))
}

// AbsoluteNumberLTE applies the LTE predicate on the "absolute_number" field.
func AbsoluteNumberLTE(v uint16) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldAbsoluteNumber, v))
}

// AbsoluteNumberIsNil applies the IsNil predicate on the "absolute_number" field.
func AbsoluteNumberIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldAbsoluteNumber))
}

// AbsoluteNumberNotNil applies the NotNil predicate on the "absolute_number" field.
func AbsoluteNumberNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldAbsoluteNumber))
}

// GrabFailuresEQ applies the EQ predicate on the "grab_failures" field.
func GrabFailuresEQ(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldGrabFailures, v))
}

// GrabFailuresNEQ applies the NEQ predicate on the "grab_failures" field.
func GrabFailuresNEQ(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldGrabFailures, v))
}

// GrabFailuresIn applies the In predicate on the "grab_failures" field.
func GrabFailuresIn(vs ...uint8) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldGrabFailures, vs...))
}

// GrabFailuresNotIn applies the NotIn predicate on the "grab_failures" field.
func GrabFailuresNotIn(vs ...uint8) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldGrabFailures, vs...))
}

// GrabFailuresGT applies the GT predicate on the "grab_failures" field.
func GrabFailuresGT(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldGrabFailures, v))
}

// GrabFailuresGTE applies the GTE predicate on the "grab_failures" field.
func GrabFailuresGTE(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldGrabFailures, v))
}

// GrabFailuresLT applies the LT predicate on the "grab_failures" field.
func GrabFailuresLT(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldGrabFailures, v))
}

// GrabFailuresLTE applies the LTE predicate on the "grab_failures" field.
func GrabFailuresLTE(v uint8) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldGrabFailures, v))
}

// LastSearchAtEQ applies the EQ predicate on the "last_search_at" field.
func LastSearchAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldLastSearchAt, v))
}

// LastSearchAtNEQ applies the NEQ predicate on the "last_search_at" field.
func LastSearchAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldLastSearchAt, v))
}

// LastSearchAtIn applies the In predicate on the "last_search_at" field.
func LastSearchAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldLastSearchAt, vs...))
}

// LastSearchAtNotIn applies the NotIn predicate on the "last_search_at" field.
func LastSearchAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldLastSearchAt, vs...))
}

// LastSearchAtGT applies the GT predicate on the "last_search_at" field.
func LastSearchAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldLastSearchAt, v))
}

// LastSearchAtGTE applies the GTE predicate on the "last_search_at" field.
func LastSearchAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldLastSearchAt, v))
}

// LastSearchAtLT applies the LT predicate on the "last_search_at" field.
func LastSearchAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldLastSearchAt, v))
}

// LastSearchAtLTE applies the LTE predicate on the "last_search_at" field.
func LastSearchAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldLastSearchAt, v))
}

// LastSearchAtIsNil applies the IsNil predicate on the "last_search_at" field.
func LastSearchAtIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldLastSearchAt))
}

// LastSearchAtNotNil applies the NotNil predicate on the "last_search_at" field.
func LastSearchAtNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldLastSearchAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldStatus, vs...))
}

// HasSeason applies the HasEdge predicate on the "season" edge.
func HasSeason() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SeasonTable, SeasonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeasonWith applies the HasEdge predicate on the "season" edge with a given conditions (other predicates).
func HasSeasonWith(preds ...predicate.Season) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newSeasonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDownloadRecords applies the HasEdge predicate on the "download_records" edge.
func HasDownloadRecords() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, DownloadRecordsTable, DownloadRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDownloadRecordsWith applies the HasEdge predicate on the "download_records" edge with a given conditions (other predicates).
func HasDownloadRecordsWith(preds ...predicate.DownloadRecord) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newDownloadRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnchoredDownloadRecords applies the HasEdge predicate on the "anchored_download_records" edge.
func HasAnchoredDownloadRecords() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnchoredDownloadRecordsTable, AnchoredDownloadRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnchoredDownloadRecordsWith applies the HasEdge predicate on the "anchored_download_records" edge with a given conditions (other predicates).
func HasAnchoredDownloadRecordsWith(preds ...predicate.DownloadRecord) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newAnchoredDownloadRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMediaFiles applies the HasEdge predicate on the "media_files" edge.
func HasMediaFiles() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MediaFilesTable, MediaFilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMediaFilesWith applies the HasEdge predicate on the "media_files" edge with a given conditions (other predicates).
func HasMediaFilesWith(preds ...predicate.MediaFile) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newMediaFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.MediaEvent) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.NotPredicates(p))
}
