// Code generated by ent, DO NOT EDIT.

package downloadrecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the downloadrecord type in the database.
	Label = "download_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldQuality holds the string denoting the quality field in the database.
	FieldQuality = "quality"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTorrentHash holds the string denoting the torrent_hash field in the database.
	FieldTorrentHash = "torrent_hash"
	// FieldReleaseGroup holds the string denoting the release_group field in the database.
	FieldReleaseGroup = "release_group"
	// FieldSavePath holds the string denoting the save_path field in the database.
	FieldSavePath = "save_path"
	// FieldImportAttempts holds the string denoting the import_attempts field in the database.
	FieldImportAttempts = "import_attempts"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldImportedAt holds the string denoting the imported_at field in the database.
	FieldImportedAt = "imported_at"
	// FieldIndexerName holds the string denoting the indexer_name field in the database.
	FieldIndexerName = "indexer_name"
	// FieldDownloadClientName holds the string denoting the download_client_name field in the database.
	FieldDownloadClientName = "download_client_name"
	// FieldReplaceMode holds the string denoting the replace_mode field in the database.
	FieldReplaceMode = "replace_mode"
	// FieldHoldReasons holds the string denoting the hold_reasons field in the database.
	FieldHoldReasons = "hold_reasons"
	// FieldVerificationBypassed holds the string denoting the verification_bypassed field in the database.
	FieldVerificationBypassed = "verification_bypassed"
	// FieldSelectedFiles holds the string denoting the selected_files field in the database.
	FieldSelectedFiles = "selected_files"
	// FieldSelectedBytes holds the string denoting the selected_bytes field in the database.
	FieldSelectedBytes = "selected_bytes"
	// FieldSelectionState holds the string denoting the selection_state field in the database.
	FieldSelectionState = "selection_state"
	// EdgeMovie holds the string denoting the movie edge name in mutations.
	EdgeMovie = "movie"
	// EdgeAnchorEpisode holds the string denoting the anchor_episode edge name in mutations.
	EdgeAnchorEpisode = "anchor_episode"
	// EdgeEpisodes holds the string denoting the episodes edge name in mutations.
	EdgeEpisodes = "episodes"
	// Table holds the table name of the downloadrecord in the database.
	Table = "download_records"
	// MovieTable is the table that holds the movie relation/edge.
	MovieTable = "download_records"
	// MovieInverseTable is the table name for the Movie entity.
	// It exists in this package in order to avoid circular dependency with the "movie" package.
	MovieInverseTable = "movies"
	// MovieColumn is the table column denoting the movie relation/edge.
	MovieColumn = "movie_download_records"
	// AnchorEpisodeTable is the table that holds the anchor_episode relation/edge.
	AnchorEpisodeTable = "download_records"
	// AnchorEpisodeInverseTable is the table name for the Episode entity.
	// It exists in this package in order to avoid circular dependency with the "episode" package.
	AnchorEpisodeInverseTable = "episodes"
	// AnchorEpisodeColumn is the table column denoting the anchor_episode relation/edge.
	AnchorEpisodeColumn = "episode_download_records"
	// EpisodesTable is the table that holds the episodes relation/edge. The primary key declared below.
	EpisodesTable = "download_record_episodes"
	// EpisodesInverseTable is the table name for the Episode entity.
	// It exists in this package in order to avoid circular dependency with the "episode" package.
	EpisodesInverseTable = "episodes"
)

// Columns holds all SQL columns for downloadrecord fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTitle,
	FieldQuality,
	FieldSize,
	FieldStatus,
	FieldTorrentHash,
	FieldReleaseGroup,
	FieldSavePath,
	FieldImportAttempts,
	FieldFailureReason,
	FieldImportedAt,
	FieldIndexerName,
	FieldDownloadClientName,
	FieldReplaceMode,
	FieldHoldReasons,
	FieldVerificationBypassed,
	FieldSelectedFiles,
	FieldSelectedBytes,
	FieldSelectionState,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "download_records"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"episode_download_records",
	"movie_download_records",
}

var (
	// EpisodesPrimaryKey and EpisodesColumn2 are the table columns denoting the
	// primary key for the episodes relation (M2M).
	EpisodesPrimaryKey = []string{"episode_id", "download_record_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultImportAttempts holds the default value on creation for the "import_attempts" field.
	DefaultImportAttempts uint8
	// DefaultVerificationBypassed holds the default value on creation for the "verification_bypassed" field.
	DefaultVerificationBypassed bool
)

// Status defines the type for the "status" enum field.
type Status string

// StatusDownloading is the default value of the Status enum.
const DefaultStatus = StatusDownloading

// Status values.
const (
	StatusDownloading Status = "downloading"
	StatusImporting   Status = "importing"
	StatusCompleted   Status = "completed"
	StatusFailed      Status = "failed"
	StatusPending     Status = "pending"
	StatusDismissed   Status = "dismissed"
	StatusHeld        Status = "held"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDownloading, StatusImporting, StatusCompleted, StatusFailed, StatusPending, StatusDismissed, StatusHeld:
		return nil
	default:
		return fmt.Errorf("downloadrecord: invalid enum value for status field: %q", s)
	}
}

// ReplaceMode defines the type for the "replace_mode" enum field.
type ReplaceMode string

// ReplaceModeNone is the default value of the ReplaceMode enum.
const DefaultReplaceMode = ReplaceModeNone

// ReplaceMode values.
const (
	ReplaceModeNone     ReplaceMode = "none"
	ReplaceModeUpgrades ReplaceMode = "upgrades"
	ReplaceModeAll      ReplaceMode = "all"
)

func (rm ReplaceMode) String() string {
	return string(rm)
}

// ReplaceModeValidator is a validator for the "replace_mode" field enum values. It is called by the builders before save.
func ReplaceModeValidator(rm ReplaceMode) error {
	switch rm {
	case ReplaceModeNone, ReplaceModeUpgrades, ReplaceModeAll:
		return nil
	default:
		return fmt.Errorf("downloadrecord: invalid enum value for replace_mode field: %q", rm)
	}
}

// SelectionState defines the type for the "selection_state" enum field.
type SelectionState string

// SelectionStateSkipped is the default value of the SelectionState enum.
const DefaultSelectionState = SelectionStateSkipped

// SelectionState values.
const (
	SelectionStatePending     SelectionState = "pending"
	SelectionStateApplied     SelectionState = "applied"
	SelectionStateUnsupported SelectionState = "unsupported"
	SelectionStateSkipped     SelectionState = "skipped"
)

func (ss SelectionState) String() string {
	return string(ss)
}

// SelectionStateValidator is a validator for the "selection_state" field enum values. It is called by the builders before save.
func SelectionStateValidator(ss SelectionState) error {
	switch ss {
	case SelectionStatePending, SelectionStateApplied, SelectionStateUnsupported, SelectionStateSkipped:
		return nil
	default:
		return fmt.Errorf("downloadrecord: invalid enum value for selection_state field: %q", ss)
	}
}

// OrderOption defines the ordering options for the DownloadRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByQuality orders the results by the quality field.
func ByQuality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuality, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTorrentHash orders the results by the torrent_hash field.
func ByTorrentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTorrentHash, opts...).ToFunc()
}

// ByReleaseGroup orders the results by the release_group field.
func ByReleaseGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseGroup, opts...).ToFunc()
}

// BySavePath orders the results by the save_path field.
func BySavePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSavePath, opts...).ToFunc()
}

// ByImportAttempts orders the results by the import_attempts field.
func ByImportAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportAttempts, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByImportedAt orders the results by the imported_at field.
func ByImportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedAt, opts...).ToFunc()
}

// ByIndexerName orders the results by the indexer_name field.
func ByIndexerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndexerName, opts...).ToFunc()
}

// ByDownloadClientName orders the results by the download_client_name field.
func ByDownloadClientName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadClientName, opts...).ToFunc()
}

// ByReplaceMode orders the results by the replace_mode field.
func ByReplaceMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplaceMode, opts...).ToFunc()
}

// ByVerificationBypassed orders the results by the verification_bypassed field.
func ByVerificationBypassed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerificationBypassed, opts...).ToFunc()
}

// BySelectedBytes orders the results by the selected_bytes field.
func BySelectedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectedBytes, opts...).ToFunc()
}

// BySelectionState orders the results by the selection_state field.
func BySelectionState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectionState, opts...).ToFunc()
}

// ByMovieField orders the results by movie field.
func ByMovieField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMovieStep(), sql.OrderByField(field, opts...))
	}
}

// ByAnchorEpisodeField orders the results by anchor_episode field.
func ByAnchorEpisodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnchorEpisodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByEpisodesCount orders the results by episodes count.
func ByEpisodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEpisodesStep(), opts...)
	}
}

// ByEpisodes orders the results by episodes terms.
func ByEpisodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEpisodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMovieStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MovieInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MovieTable, MovieColumn),
	)
}
func newAnchorEpisodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnchorEpisodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AnchorEpisodeTable, AnchorEpisodeColumn),
	)
}
func newEpisodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EpisodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, EpisodesTable, EpisodesPrimaryKey...),
	)
}
