// Code generated by ent, DO NOT EDIT.

package downloadrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datahearth/streamline/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldUpdateTime, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldTitle, v))
}

// Quality applies equality check predicate on the "quality" field. It's identical to QualityEQ.
func Quality(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldQuality, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSize, v))
}

// TorrentHash applies equality check predicate on the "torrent_hash" field. It's identical to TorrentHashEQ.
func TorrentHash(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldTorrentHash, v))
}

// ReleaseGroup applies equality check predicate on the "release_group" field. It's identical to ReleaseGroupEQ.
func ReleaseGroup(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldReleaseGroup, v))
}

// SavePath applies equality check predicate on the "save_path" field. It's identical to SavePathEQ.
func SavePath(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSavePath, v))
}

// ImportAttempts applies equality check predicate on the "import_attempts" field. It's identical to ImportAttemptsEQ.
func ImportAttempts(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldImportAttempts, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldFailureReason, v))
}

// ImportedAt applies equality check predicate on the "imported_at" field. It's identical to ImportedAtEQ.
func ImportedAt(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldImportedAt, v))
}

// IndexerName applies equality check predicate on the "indexer_name" field. It's identical to IndexerNameEQ.
func IndexerName(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldIndexerName, v))
}

// DownloadClientName applies equality check predicate on the "download_client_name" field. It's identical to DownloadClientNameEQ.
func DownloadClientName(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldDownloadClientName, v))
}

// VerificationBypassed applies equality check predicate on the "verification_bypassed" field. It's identical to VerificationBypassedEQ.
func VerificationBypassed(v bool) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldVerificationBypassed, v))
}

// SelectedBytes applies equality check predicate on the "selected_bytes" field. It's identical to SelectedBytesEQ.
func SelectedBytes(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSelectedBytes, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldUpdateTime, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldTitle, v))
}

// QualityEQ applies the EQ predicate on the "quality" field.
func QualityEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldQuality, v))
}

// QualityNEQ applies the NEQ predicate on the "quality" field.
func QualityNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldQuality, v))
}

// QualityIn applies the In predicate on the "quality" field.
func QualityIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldQuality, vs...))
}

// QualityNotIn applies the NotIn predicate on the "quality" field.
func QualityNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldQuality, vs...))
}

// QualityGT applies the GT predicate on the "quality" field.
func QualityGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldQuality, v))
}

// QualityGTE applies the GTE predicate on the "quality" field.
func QualityGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldQuality, v))
}

// QualityLT applies the LT predicate on the "quality" field.
func QualityLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldQuality, v))
}

// QualityLTE applies the LTE predicate on the "quality" field.
func QualityLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldQuality, v))
}

// QualityContains applies the Contains predicate on the "quality" field.
func QualityContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldQuality, v))
}

// QualityHasPrefix applies the HasPrefix predicate on the "quality" field.
func QualityHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldQuality, v))
}

// QualityHasSuffix applies the HasSuffix predicate on the "quality" field.
func QualityHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldQuality, v))
}

// QualityIsNil applies the IsNil predicate on the "quality" field.
func QualityIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldQuality))
}

// QualityNotNil applies the NotNil predicate on the "quality" field.
func QualityNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldQuality))
}

// QualityEqualFold applies the EqualFold predicate on the "quality" field.
func QualityEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldQuality, v))
}

// QualityContainsFold applies the ContainsFold predicate on the "quality" field.
func QualityContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldQuality, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldSize))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// TorrentHashEQ applies the EQ predicate on the "torrent_hash" field.
func TorrentHashEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldTorrentHash, v))
}

// TorrentHashNEQ applies the NEQ predicate on the "torrent_hash" field.
func TorrentHashNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldTorrentHash, v))
}

// TorrentHashIn applies the In predicate on the "torrent_hash" field.
func TorrentHashIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldTorrentHash, vs...))
}

// TorrentHashNotIn applies the NotIn predicate on the "torrent_hash" field.
func TorrentHashNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldTorrentHash, vs...))
}

// TorrentHashGT applies the GT predicate on the "torrent_hash" field.
func TorrentHashGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldTorrentHash, v))
}

// TorrentHashGTE applies the GTE predicate on the "torrent_hash" field.
func TorrentHashGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldTorrentHash, v))
}

// TorrentHashLT applies the LT predicate on the "torrent_hash" field.
func TorrentHashLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldTorrentHash, v))
}

// TorrentHashLTE applies the LTE predicate on the "torrent_hash" field.
func TorrentHashLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldTorrentHash, v))
}

// TorrentHashContains applies the Contains predicate on the "torrent_hash" field.
func TorrentHashContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldTorrentHash, v))
}

// TorrentHashHasPrefix applies the HasPrefix predicate on the "torrent_hash" field.
func TorrentHashHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldTorrentHash, v))
}

// TorrentHashHasSuffix applies the HasSuffix predicate on the "torrent_hash" field.
func TorrentHashHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldTorrentHash, v))
}

// TorrentHashIsNil applies the IsNil predicate on the "torrent_hash" field.
func TorrentHashIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldTorrentHash))
}

// TorrentHashNotNil applies the NotNil predicate on the "torrent_hash" field.
func TorrentHashNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldTorrentHash))
}

// TorrentHashEqualFold applies the EqualFold predicate on the "torrent_hash" field.
func TorrentHashEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldTorrentHash, v))
}

// TorrentHashContainsFold applies the ContainsFold predicate on the "torrent_hash" field.
func TorrentHashContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldTorrentHash, v))
}

// ReleaseGroupEQ applies the EQ predicate on the "release_group" field.
func ReleaseGroupEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldReleaseGroup, v))
}

// ReleaseGroupNEQ applies the NEQ predicate on the "release_group" field.
func ReleaseGroupNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldReleaseGroup, v))
}

// ReleaseGroupIn applies the In predicate on the "release_group" field.
func ReleaseGroupIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldReleaseGroup, vs...))
}

// ReleaseGroupNotIn applies the NotIn predicate on the "release_group" field.
func ReleaseGroupNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldReleaseGroup, vs...))
}

// ReleaseGroupGT applies the GT predicate on the "release_group" field.
func ReleaseGroupGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldReleaseGroup, v))
}

// ReleaseGroupGTE applies the GTE predicate on the "release_group" field.
func ReleaseGroupGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldReleaseGroup, v))
}

// ReleaseGroupLT applies the LT predicate on the "release_group" field.
func ReleaseGroupLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldReleaseGroup, v))
}

// ReleaseGroupLTE applies the LTE predicate on the "release_group" field.
func ReleaseGroupLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldReleaseGroup, v))
}

// ReleaseGroupContains applies the Contains predicate on the "release_group" field.
func ReleaseGroupContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldReleaseGroup, v))
}

// ReleaseGroupHasPrefix applies the HasPrefix predicate on the "release_group" field.
func ReleaseGroupHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldReleaseGroup, v))
}

// ReleaseGroupHasSuffix applies the HasSuffix predicate on the "release_group" field.
func ReleaseGroupHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldReleaseGroup, v))
}

// ReleaseGroupIsNil applies the IsNil predicate on the "release_group" field.
func ReleaseGroupIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldReleaseGroup))
}

// ReleaseGroupNotNil applies the NotNil predicate on the "release_group" field.
func ReleaseGroupNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldReleaseGroup))
}

// ReleaseGroupEqualFold applies the EqualFold predicate on the "release_group" field.
func ReleaseGroupEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldReleaseGroup, v))
}

// ReleaseGroupContainsFold applies the ContainsFold predicate on the "release_group" field.
func ReleaseGroupContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldReleaseGroup, v))
}

// SavePathEQ applies the EQ predicate on the "save_path" field.
func SavePathEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSavePath, v))
}

// SavePathNEQ applies the NEQ predicate on the "save_path" field.
func SavePathNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldSavePath, v))
}

// SavePathIn applies the In predicate on the "save_path" field.
func SavePathIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldSavePath, vs...))
}

// SavePathNotIn applies the NotIn predicate on the "save_path" field.
func SavePathNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldSavePath, vs...))
}

// SavePathGT applies the GT predicate on the "save_path" field.
func SavePathGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldSavePath, v))
}

// SavePathGTE applies the GTE predicate on the "save_path" field.
func SavePathGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldSavePath, v))
}

// SavePathLT applies the LT predicate on the "save_path" field.
func SavePathLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldSavePath, v))
}

// SavePathLTE applies the LTE predicate on the "save_path" field.
func SavePathLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldSavePath, v))
}

// SavePathContains applies the Contains predicate on the "save_path" field.
func SavePathContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldSavePath, v))
}

// SavePathHasPrefix applies the HasPrefix predicate on the "save_path" field.
func SavePathHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldSavePath, v))
}

// SavePathHasSuffix applies the HasSuffix predicate on the "save_path" field.
func SavePathHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldSavePath, v))
}

// SavePathIsNil applies the IsNil predicate on the "save_path" field.
func SavePathIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldSavePath))
}

// SavePathNotNil applies the NotNil predicate on the "save_path" field.
func SavePathNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldSavePath))
}

// SavePathEqualFold applies the EqualFold predicate on the "save_path" field.
func SavePathEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldSavePath, v))
}

// SavePathContainsFold applies the ContainsFold predicate on the "save_path" field.
func SavePathContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldSavePath, v))
}

// ImportAttemptsEQ applies the EQ predicate on the "import_attempts" field.
func ImportAttemptsEQ(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldImportAttempts, v))
}

// ImportAttemptsNEQ applies the NEQ predicate on the "import_attempts" field.
func ImportAttemptsNEQ(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldImportAttempts, v))
}

// ImportAttemptsIn applies the In predicate on the "import_attempts" field.
func ImportAttemptsIn(vs ...uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldImportAttempts, vs...))
}

// ImportAttemptsNotIn applies the NotIn predicate on the "import_attempts" field.
func ImportAttemptsNotIn(vs ...uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldImportAttempts, vs...))
}

// ImportAttemptsGT applies the GT predicate on the "import_attempts" field.
func ImportAttemptsGT(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldImportAttempts, v))
}

// ImportAttemptsGTE applies the GTE predicate on the "import_attempts" field.
func ImportAttemptsGTE(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldImportAttempts, v))
}

// ImportAttemptsLT applies the LT predicate on the "import_attempts" field.
func ImportAttemptsLT(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldImportAttempts, v))
}

// ImportAttemptsLTE applies the LTE predicate on the "import_attempts" field.
func ImportAttemptsLTE(v uint8) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldImportAttempts, v))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldFailureReason, v))
}

// ImportedAtEQ applies the EQ predicate on the "imported_at" field.
func ImportedAtEQ(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldImportedAt, v))
}

// ImportedAtNEQ applies the NEQ predicate on the "imported_at" field.
func ImportedAtNEQ(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldImportedAt, v))
}

// ImportedAtIn applies the In predicate on the "imported_at" field.
func ImportedAtIn(vs ...time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldImportedAt, vs...))
}

// ImportedAtNotIn applies the NotIn predicate on the "imported_at" field.
func ImportedAtNotIn(vs ...time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldImportedAt, vs...))
}

// ImportedAtGT applies the GT predicate on the "imported_at" field.
func ImportedAtGT(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldImportedAt, v))
}

// ImportedAtGTE applies the GTE predicate on the "imported_at" field.
func ImportedAtGTE(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldImportedAt, v))
}

// ImportedAtLT applies the LT predicate on the "imported_at" field.
func ImportedAtLT(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldImportedAt, v))
}

// ImportedAtLTE applies the LTE predicate on the "imported_at" field.
func ImportedAtLTE(v time.Time) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldImportedAt, v))
}

// ImportedAtIsNil applies the IsNil predicate on the "imported_at" field.
func ImportedAtIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldImportedAt))
}

// ImportedAtNotNil applies the NotNil predicate on the "imported_at" field.
func ImportedAtNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldImportedAt))
}

// IndexerNameEQ applies the EQ predicate on the "indexer_name" field.
func IndexerNameEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldIndexerName, v))
}

// IndexerNameNEQ applies the NEQ predicate on the "indexer_name" field.
func IndexerNameNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldIndexerName, v))
}

// IndexerNameIn applies the In predicate on the "indexer_name" field.
func IndexerNameIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldIndexerName, vs...))
}

// IndexerNameNotIn applies the NotIn predicate on the "indexer_name" field.
func IndexerNameNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldIndexerName, vs...))
}

// IndexerNameGT applies the GT predicate on the "indexer_name" field.
func IndexerNameGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldIndexerName, v))
}

// IndexerNameGTE applies the GTE predicate on the "indexer_name" field.
func IndexerNameGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldIndexerName, v))
}

// IndexerNameLT applies the LT predicate on the "indexer_name" field.
func IndexerNameLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldIndexerName, v))
}

// IndexerNameLTE applies the LTE predicate on the "indexer_name" field.
func IndexerNameLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldIndexerName, v))
}

// IndexerNameContains applies the Contains predicate on the "indexer_name" field.
func IndexerNameContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldIndexerName, v))
}

// IndexerNameHasPrefix applies the HasPrefix predicate on the "indexer_name" field.
func IndexerNameHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldIndexerName, v))
}

// IndexerNameHasSuffix applies the HasSuffix predicate on the "indexer_name" field.
func IndexerNameHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldIndexerName, v))
}

// IndexerNameIsNil applies the IsNil predicate on the "indexer_name" field.
func IndexerNameIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldIndexerName))
}

// IndexerNameNotNil applies the NotNil predicate on the "indexer_name" field.
func IndexerNameNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldIndexerName))
}

// IndexerNameEqualFold applies the EqualFold predicate on the "indexer_name" field.
func IndexerNameEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldIndexerName, v))
}

// IndexerNameContainsFold applies the ContainsFold predicate on the "indexer_name" field.
func IndexerNameContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldIndexerName, v))
}

// DownloadClientNameEQ applies the EQ predicate on the "download_client_name" field.
func DownloadClientNameEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldDownloadClientName, v))
}

// DownloadClientNameNEQ applies the NEQ predicate on the "download_client_name" field.
func DownloadClientNameNEQ(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldDownloadClientName, v))
}

// DownloadClientNameIn applies the In predicate on the "download_client_name" field.
func DownloadClientNameIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldDownloadClientName, vs...))
}

// DownloadClientNameNotIn applies the NotIn predicate on the "download_client_name" field.
func DownloadClientNameNotIn(vs ...string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldDownloadClientName, vs...))
}

// DownloadClientNameGT applies the GT predicate on the "download_client_name" field.
func DownloadClientNameGT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldDownloadClientName, v))
}

// DownloadClientNameGTE applies the GTE predicate on the "download_client_name" field.
func DownloadClientNameGTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldDownloadClientName, v))
}

// DownloadClientNameLT applies the LT predicate on the "download_client_name" field.
func DownloadClientNameLT(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldDownloadClientName, v))
}

// DownloadClientNameLTE applies the LTE predicate on the "download_client_name" field.
func DownloadClientNameLTE(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldDownloadClientName, v))
}

// DownloadClientNameContains applies the Contains predicate on the "download_client_name" field.
func DownloadClientNameContains(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContains(FieldDownloadClientName, v))
}

// DownloadClientNameHasPrefix applies the HasPrefix predicate on the "download_client_name" field.
func DownloadClientNameHasPrefix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasPrefix(FieldDownloadClientName, v))
}

// DownloadClientNameHasSuffix applies the HasSuffix predicate on the "download_client_name" field.
func DownloadClientNameHasSuffix(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldHasSuffix(FieldDownloadClientName, v))
}

// DownloadClientNameIsNil applies the IsNil predicate on the "download_client_name" field.
func DownloadClientNameIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldDownloadClientName))
}

// DownloadClientNameNotNil applies the NotNil predicate on the "download_client_name" field.
func DownloadClientNameNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldDownloadClientName))
}

// DownloadClientNameEqualFold applies the EqualFold predicate on the "download_client_name" field.
func DownloadClientNameEqualFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEqualFold(FieldDownloadClientName, v))
}

// DownloadClientNameContainsFold applies the ContainsFold predicate on the "download_client_name" field.
func DownloadClientNameContainsFold(v string) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldContainsFold(FieldDownloadClientName, v))
}

// ReplaceModeEQ applies the EQ predicate on the "replace_mode" field.
func ReplaceModeEQ(v ReplaceMode) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldReplaceMode, v))
}

// ReplaceModeNEQ applies the NEQ predicate on the "replace_mode" field.
func ReplaceModeNEQ(v ReplaceMode) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldReplaceMode, v))
}

// ReplaceModeIn applies the In predicate on the "replace_mode" field.
func ReplaceModeIn(vs ...ReplaceMode) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldReplaceMode, vs...))
}

// ReplaceModeNotIn applies the NotIn predicate on the "replace_mode" field.
func ReplaceModeNotIn(vs ...ReplaceMode) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldReplaceMode, vs...))
}

// HoldReasonsIsNil applies the IsNil predicate on the "hold_reasons" field.
func HoldReasonsIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldHoldReasons))
}

// HoldReasonsNotNil applies the NotNil predicate on the "hold_reasons" field.
func HoldReasonsNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldHoldReasons))
}

// VerificationBypassedEQ applies the EQ predicate on the "verification_bypassed" field.
func VerificationBypassedEQ(v bool) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldVerificationBypassed, v))
}

// VerificationBypassedNEQ applies the NEQ predicate on the "verification_bypassed" field.
func VerificationBypassedNEQ(v bool) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldVerificationBypassed, v))
}

// SelectedFilesIsNil applies the IsNil predicate on the "selected_files" field.
func SelectedFilesIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldSelectedFiles))
}

// SelectedFilesNotNil applies the NotNil predicate on the "selected_files" field.
func SelectedFilesNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldSelectedFiles))
}

// SelectedBytesEQ applies the EQ predicate on the "selected_bytes" field.
func SelectedBytesEQ(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSelectedBytes, v))
}

// SelectedBytesNEQ applies the NEQ predicate on the "selected_bytes" field.
func SelectedBytesNEQ(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldSelectedBytes, v))
}

// SelectedBytesIn applies the In predicate on the "selected_bytes" field.
func SelectedBytesIn(vs ...int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldSelectedBytes, vs...))
}

// SelectedBytesNotIn applies the NotIn predicate on the "selected_bytes" field.
func SelectedBytesNotIn(vs ...int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldSelectedBytes, vs...))
}

// SelectedBytesGT applies the GT predicate on the "selected_bytes" field.
func SelectedBytesGT(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGT(FieldSelectedBytes, v))
}

// SelectedBytesGTE applies the GTE predicate on the "selected_bytes" field.
func SelectedBytesGTE(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldGTE(FieldSelectedBytes, v))
}

// SelectedBytesLT applies the LT predicate on the "selected_bytes" field.
func SelectedBytesLT(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLT(FieldSelectedBytes, v))
}

// SelectedBytesLTE applies the LTE predicate on the "selected_bytes" field.
func SelectedBytesLTE(v int64) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldLTE(FieldSelectedBytes, v))
}

// SelectedBytesIsNil applies the IsNil predicate on the "selected_bytes" field.
func SelectedBytesIsNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIsNull(FieldSelectedBytes))
}

// SelectedBytesNotNil applies the NotNil predicate on the "selected_bytes" field.
func SelectedBytesNotNil() predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotNull(FieldSelectedBytes))
}

// SelectionStateEQ applies the EQ predicate on the "selection_state" field.
func SelectionStateEQ(v SelectionState) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldEQ(FieldSelectionState, v))
}

// SelectionStateNEQ applies the NEQ predicate on the "selection_state" field.
func SelectionStateNEQ(v SelectionState) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNEQ(FieldSelectionState, v))
}

// SelectionStateIn applies the In predicate on the "selection_state" field.
func SelectionStateIn(vs ...SelectionState) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldIn(FieldSelectionState, vs...))
}

// SelectionStateNotIn applies the NotIn predicate on the "selection_state" field.
func SelectionStateNotIn(vs ...SelectionState) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.FieldNotIn(FieldSelectionState, vs...))
}

// HasMovie applies the HasEdge predicate on the "movie" edge.
func HasMovie() predicate.DownloadRecord {
	return predicate.DownloadRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MovieTable, MovieColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMovieWith applies the HasEdge predicate on the "movie" edge with a given conditions (other predicates).
func HasMovieWith(preds ...predicate.Movie) predicate.DownloadRecord {
	return predicate.DownloadRecord(func(s *sql.Selector) {
		step := newMovieStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnchorEpisode applies the HasEdge predicate on the "anchor_episode" edge.
func HasAnchorEpisode() predicate.DownloadRecord {
	return predicate.DownloadRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AnchorEpisodeTable, AnchorEpisodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnchorEpisodeWith applies the HasEdge predicate on the "anchor_episode" edge with a given conditions (other predicates).
func HasAnchorEpisodeWith(preds ...predicate.Episode) predicate.DownloadRecord {
	return predicate.DownloadRecord(func(s *sql.Selector) {
		step := newAnchorEpisodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEpisodes applies the HasEdge predicate on the "episodes" edge.
func HasEpisodes() predicate.DownloadRecord {
	return predicate.DownloadRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, EpisodesTable, EpisodesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEpisodesWith applies the HasEdge predicate on the "episodes" edge with a given conditions (other predicates).
func HasEpisodesWith(preds ...predicate.Episode) predicate.DownloadRecord {
	return predicate.DownloadRecord(func(s *sql.Selector) {
		step := newEpisodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DownloadRecord) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DownloadRecord) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DownloadRecord) predicate.DownloadRecord {
	return predicate.DownloadRecord(sql.NotPredicates(p))
}
