// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeString},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_api_keys", Type: field.TypeUint32},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_key_hash",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
			{
				Name:    "apikey_user_api_keys",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[6]},
			},
		},
	}
	// CreditsColumns holds the columns for the "credits" table.
	CreditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "character", Type: field.TypeString, Nullable: true},
		{Name: "order", Type: field.TypeUint8, Nullable: true, Default: 0},
		{Name: "movie_credits", Type: field.TypeUint32, Nullable: true},
		{Name: "person_credits", Type: field.TypeUint32},
		{Name: "tv_show_credits", Type: field.TypeUint32, Nullable: true},
	}
	// CreditsTable holds the schema information for the "credits" table.
	CreditsTable = &schema.Table{
		Name:       "credits",
		Columns:    CreditsColumns,
		PrimaryKey: []*schema.Column{CreditsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "credits_movies_credits",
				Columns:    []*schema.Column{CreditsColumns[5]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "credits_persons_credits",
				Columns:    []*schema.Column{CreditsColumns[6]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "credits_tv_shows_credits",
				Columns:    []*schema.Column{CreditsColumns[7]},
				RefColumns: []*schema.Column{TvShowsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "credit_person_credits",
				Unique:  false,
				Columns: []*schema.Column{CreditsColumns[6]},
			},
			{
				Name:    "credit_movie_credits",
				Unique:  false,
				Columns: []*schema.Column{CreditsColumns[5]},
			},
			{
				Name:    "credit_tv_show_credits",
				Unique:  false,
				Columns: []*schema.Column{CreditsColumns[7]},
			},
		},
	}
	// DownloadRecordsColumns holds the columns for the "download_records" table.
	DownloadRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "quality", Type: field.TypeString, Nullable: true},
		{Name: "size", Type: field.TypeInt64, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"downloading", "importing", "completed", "failed", "pending", "dismissed", "held"}, Default: "downloading"},
		{Name: "torrent_hash", Type: field.TypeString, Nullable: true},
		{Name: "release_group", Type: field.TypeString, Nullable: true},
		{Name: "save_path", Type: field.TypeString, Nullable: true},
		{Name: "import_attempts", Type: field.TypeUint8, Default: 0},
		{Name: "failure_reason", Type: field.TypeString, Nullable: true},
		{Name: "imported_at", Type: field.TypeTime, Nullable: true},
		{Name: "indexer_name", Type: field.TypeString, Nullable: true},
		{Name: "download_client_name", Type: field.TypeString, Nullable: true},
		{Name: "replace_mode", Type: field.TypeEnum, Enums: []string{"none", "upgrades", "all"}, Default: "none"},
		{Name: "hold_reasons", Type: field.TypeJSON, Nullable: true},
		{Name: "verification_bypassed", Type: field.TypeBool, Default: false},
		{Name: "selected_files", Type: field.TypeJSON, Nullable: true},
		{Name: "selected_bytes", Type: field.TypeInt64, Nullable: true},
		{Name: "selection_state", Type: field.TypeEnum, Enums: []string{"pending", "applied", "unsupported", "skipped"}, Default: "skipped"},
		{Name: "episode_download_records", Type: field.TypeUint32, Nullable: true},
		{Name: "movie_download_records", Type: field.TypeUint32, Nullable: true},
	}
	// DownloadRecordsTable holds the schema information for the "download_records" table.
	DownloadRecordsTable = &schema.Table{
		Name:       "download_records",
		Columns:    DownloadRecordsColumns,
		PrimaryKey: []*schema.Column{DownloadRecordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "download_records_episodes_anchored_download_records",
				Columns:    []*schema.Column{DownloadRecordsColumns[21]},
				RefColumns: []*schema.Column{EpisodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "download_records_movies_download_records",
				Columns:    []*schema.Column{DownloadRecordsColumns[22]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "downloadrecord_selection_state",
				Unique:  false,
				Columns: []*schema.Column{DownloadRecordsColumns[20]},
			},
			{
				Name:    "downloadrecord_status",
				Unique:  false,
				Columns: []*schema.Column{DownloadRecordsColumns[6]},
			},
			{
				Name:    "downloadrecord_torrent_hash",
				Unique:  false,
				Columns: []*schema.Column{DownloadRecordsColumns[7]},
			},
			{
				Name:    "downloadrecord_update_time_id",
				Unique:  false,
				Columns: []*schema.Column{DownloadRecordsColumns[2], DownloadRecordsColumns[0]},
			},
			{
				Name:    "downloadrecord_movie_download_records",
				Unique:  false,
				Columns: []*schema.Column{DownloadRecordsColumns[22]},
			},
			{
				Name:    "downloadrecord_episode_download_records",
				Unique:  false,
				Columns: []*schema.Column{DownloadRecordsColumns[21]},
			},
		},
	}
	// EpisodesColumns holds the columns for the "episodes" table.
	EpisodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "number", Type: field.TypeUint16},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "overview", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "air_date", Type: field.TypeTime, Nullable: true},
		{Name: "monitored", Type: field.TypeBool, Default: true},
		{Name: "absolute_number", Type: field.TypeUint16, Nullable: true, Default: 0},
		{Name: "grab_failures", Type: field.TypeUint8, Default: 0},
		{Name: "last_search_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"wanted", "downloading", "importing", "paused", "available", "skipped"}, Default: "wanted"},
		{Name: "season_episodes", Type: field.TypeUint32},
	}
	// EpisodesTable holds the schema information for the "episodes" table.
	EpisodesTable = &schema.Table{
		Name:       "episodes",
		Columns:    EpisodesColumns,
		PrimaryKey: []*schema.Column{EpisodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "episodes_seasons_episodes",
				Columns:    []*schema.Column{EpisodesColumns[12]},
				RefColumns: []*schema.Column{SeasonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "episode_season_episodes",
				Unique:  false,
				Columns: []*schema.Column{EpisodesColumns[12]},
			},
			{
				Name:    "episode_status",
				Unique:  false,
				Columns: []*schema.Column{EpisodesColumns[11]},
			},
		},
	}
	// ImportScansColumns holds the columns for the "import_scans" table.
	ImportScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "source_path", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"movie", "series"}, Default: "movie"},
		{Name: "mode", Type: field.TypeEnum, Enums: []string{"in_place", "rename"}},
		{Name: "import_mode", Type: field.TypeEnum, Nullable: true, Enums: []string{"hardlink", "copy", "move"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "awaiting_review", "committing", "completed", "cancelled", "failed"}, Default: "running"},
		{Name: "total_count", Type: field.TypeUint32, Default: 0},
		{Name: "processed_count", Type: field.TypeUint32, Default: 0},
		{Name: "commit_success_count", Type: field.TypeUint32, Default: 0},
		{Name: "commit_failed_count", Type: field.TypeUint32, Default: 0},
		{Name: "failure_reason", Type: field.TypeString, Nullable: true},
		{Name: "scanned_at", Type: field.TypeTime, Nullable: true},
		{Name: "committed_at", Type: field.TypeTime, Nullable: true},
	}
	// ImportScansTable holds the schema information for the "import_scans" table.
	ImportScansTable = &schema.Table{
		Name:       "import_scans",
		Columns:    ImportScansColumns,
		PrimaryKey: []*schema.Column{ImportScansColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "importscan_status",
				Unique:  false,
				Columns: []*schema.Column{ImportScansColumns[7]},
			},
			{
				Name:    "importscan_kind",
				Unique:  false,
				Columns: []*schema.Column{ImportScansColumns[4]},
			},
		},
	}
	// ImportScanFilesColumns holds the columns for the "import_scan_files" table.
	ImportScanFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "source_path", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "parsed_title", Type: field.TypeString, Nullable: true},
		{Name: "parsed_year", Type: field.TypeUint16, Nullable: true},
		{Name: "parsed_quality", Type: field.TypeString, Nullable: true},
		{Name: "parsed_release_group", Type: field.TypeString, Nullable: true},
		{Name: "classification", Type: field.TypeEnum, Enums: []string{"confirmed", "ambiguous", "unmatched", "existing"}, Default: "unmatched"},
		{Name: "candidates", Type: field.TypeJSON, Nullable: true},
		{Name: "tmdb_id", Type: field.TypeUint32, Nullable: true},
		{Name: "existing_movie_id", Type: field.TypeUint32, Nullable: true},
		{Name: "decision", Type: field.TypeEnum, Enums: []string{"pending", "accept", "skip"}, Default: "pending"},
		{Name: "decision_tmdb_id", Type: field.TypeUint32, Nullable: true},
		{Name: "outcome", Type: field.TypeEnum, Enums: []string{"pending", "created", "attached", "skipped", "failed"}, Default: "pending"},
		{Name: "outcome_message", Type: field.TypeString, Nullable: true},
		{Name: "created_movie_id", Type: field.TypeUint32, Nullable: true},
		{Name: "import_scan_files", Type: field.TypeUint32},
	}
	// ImportScanFilesTable holds the schema information for the "import_scan_files" table.
	ImportScanFilesTable = &schema.Table{
		Name:       "import_scan_files",
		Columns:    ImportScanFilesColumns,
		PrimaryKey: []*schema.Column{ImportScanFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "import_scan_files_import_scans_files",
				Columns:    []*schema.Column{ImportScanFilesColumns[18]},
				RefColumns: []*schema.Column{ImportScansColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "importscanfile_classification",
				Unique:  false,
				Columns: []*schema.Column{ImportScanFilesColumns[9]},
			},
			{
				Name:    "importscanfile_decision",
				Unique:  false,
				Columns: []*schema.Column{ImportScanFilesColumns[13]},
			},
			{
				Name:    "importscanfile_import_scan_files",
				Unique:  false,
				Columns: []*schema.Column{ImportScanFilesColumns[18]},
			},
			{
				Name:    "importscanfile_source_path",
				Unique:  false,
				Columns: []*schema.Column{ImportScanFilesColumns[3]},
			},
		},
	}
	// ImportScanShowsColumns holds the columns for the "import_scan_shows" table.
	ImportScanShowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "folder_path", Type: field.TypeString},
		{Name: "parsed_title", Type: field.TypeString, Nullable: true},
		{Name: "parsed_year", Type: field.TypeUint16, Nullable: true},
		{Name: "classification", Type: field.TypeEnum, Enums: []string{"confirmed", "ambiguous", "unmatched", "existing"}, Default: "unmatched"},
		{Name: "tvdb_id", Type: field.TypeUint32, Nullable: true},
		{Name: "candidates", Type: field.TypeJSON, Nullable: true},
		{Name: "existing_tvshow_id", Type: field.TypeUint32, Nullable: true},
		{Name: "file_count", Type: field.TypeUint16, Default: 0},
		{Name: "decision", Type: field.TypeEnum, Enums: []string{"pending", "accept", "skip"}, Default: "pending"},
		{Name: "decision_tvdb_id", Type: field.TypeUint32, Nullable: true},
		{Name: "outcome", Type: field.TypeEnum, Enums: []string{"pending", "created", "attached", "failed"}, Default: "pending"},
		{Name: "outcome_message", Type: field.TypeString, Nullable: true},
		{Name: "created_tvshow_id", Type: field.TypeUint32, Nullable: true},
		{Name: "import_scan_shows", Type: field.TypeUint32},
	}
	// ImportScanShowsTable holds the schema information for the "import_scan_shows" table.
	ImportScanShowsTable = &schema.Table{
		Name:       "import_scan_shows",
		Columns:    ImportScanShowsColumns,
		PrimaryKey: []*schema.Column{ImportScanShowsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "import_scan_shows_import_scans_shows",
				Columns:    []*schema.Column{ImportScanShowsColumns[16]},
				RefColumns: []*schema.Column{ImportScansColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "importscanshow_classification",
				Unique:  false,
				Columns: []*schema.Column{ImportScanShowsColumns[6]},
			},
			{
				Name:    "importscanshow_decision",
				Unique:  false,
				Columns: []*schema.Column{ImportScanShowsColumns[11]},
			},
			{
				Name:    "importscanshow_import_scan_shows",
				Unique:  false,
				Columns: []*schema.Column{ImportScanShowsColumns[16]},
			},
			{
				Name:    "importscanshow_folder_path",
				Unique:  false,
				Columns: []*schema.Column{ImportScanShowsColumns[3]},
			},
		},
	}
	// InvitesColumns holds the columns for the "invites" table.
	InvitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member", "request_only"}, Default: "member"},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "invite_created_by", Type: field.TypeUint32},
		{Name: "invite_used_by", Type: field.TypeUint32, Nullable: true},
	}
	// InvitesTable holds the schema information for the "invites" table.
	InvitesTable = &schema.Table{
		Name:       "invites",
		Columns:    InvitesColumns,
		PrimaryKey: []*schema.Column{InvitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invites_users_created_by",
				Columns:    []*schema.Column{InvitesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "invites_users_used_by",
				Columns:    []*schema.Column{InvitesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invite_invite_created_by",
				Unique:  false,
				Columns: []*schema.Column{InvitesColumns[8]},
			},
			{
				Name:    "invite_invite_used_by",
				Unique:  false,
				Columns: []*schema.Column{InvitesColumns[9]},
			},
		},
	}
	// MediaEventsColumns holds the columns for the "media_events" table.
	MediaEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"grabbed", "download_completed", "download_failed", "download_cancelled", "grab_widened", "imported", "import_failed", "import_held_for_review", "drift_detected", "drift_confirmed", "searched", "added", "file_renamed", "file_removed", "reidentified", "metadata_refreshed", "monitoring_changed", "request_approved", "transcode_completed", "transcode_failed", "transcode_rejected"}},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "episode_events", Type: field.TypeUint32, Nullable: true},
		{Name: "movie_events", Type: field.TypeUint32, Nullable: true},
		{Name: "tv_show_events", Type: field.TypeUint32, Nullable: true},
	}
	// MediaEventsTable holds the schema information for the "media_events" table.
	MediaEventsTable = &schema.Table{
		Name:       "media_events",
		Columns:    MediaEventsColumns,
		PrimaryKey: []*schema.Column{MediaEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_events_episodes_events",
				Columns:    []*schema.Column{MediaEventsColumns[5]},
				RefColumns: []*schema.Column{EpisodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "media_events_movies_events",
				Columns:    []*schema.Column{MediaEventsColumns[6]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "media_events_tv_shows_events",
				Columns:    []*schema.Column{MediaEventsColumns[7]},
				RefColumns: []*schema.Column{TvShowsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mediaevent_create_time",
				Unique:  false,
				Columns: []*schema.Column{MediaEventsColumns[1]},
			},
			{
				Name:    "mediaevent_type_create_time",
				Unique:  false,
				Columns: []*schema.Column{MediaEventsColumns[3], MediaEventsColumns[1]},
			},
			{
				Name:    "mediaevent_create_time_movie_events",
				Unique:  false,
				Columns: []*schema.Column{MediaEventsColumns[1], MediaEventsColumns[6]},
			},
			{
				Name:    "mediaevent_create_time_episode_events",
				Unique:  false,
				Columns: []*schema.Column{MediaEventsColumns[1], MediaEventsColumns[5]},
			},
			{
				Name:    "mediaevent_create_time_tv_show_events",
				Unique:  false,
				Columns: []*schema.Column{MediaEventsColumns[1], MediaEventsColumns[7]},
			},
		},
	}
	// MediaFilesColumns holds the columns for the "media_files" table.
	MediaFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "path", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "quality", Type: field.TypeString, Nullable: true},
		{Name: "format", Type: field.TypeString, Nullable: true},
		{Name: "release_group", Type: field.TypeString, Nullable: true},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"wizard", "orphan", "auto"}, Default: "auto"},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "missing_since", Type: field.TypeTime, Nullable: true},
		{Name: "container", Type: field.TypeString, Nullable: true},
		{Name: "duration_seconds", Type: field.TypeUint32, Nullable: true},
		{Name: "video_codec", Type: field.TypeString, Nullable: true},
		{Name: "width", Type: field.TypeUint16, Nullable: true},
		{Name: "height", Type: field.TypeUint16, Nullable: true},
		{Name: "audio_codec", Type: field.TypeString, Nullable: true},
		{Name: "audio_channels", Type: field.TypeUint8, Nullable: true},
		{Name: "bitrate", Type: field.TypeUint32, Nullable: true},
		{Name: "audio_tracks", Type: field.TypeUint8, Nullable: true},
		{Name: "audio_langs", Type: field.TypeString, Nullable: true},
		{Name: "sub_langs", Type: field.TypeString, Nullable: true},
		{Name: "probed_at", Type: field.TypeTime, Nullable: true},
		{Name: "parsed_source", Type: field.TypeString, Nullable: true},
		{Name: "parsed_resolution", Type: field.TypeString, Nullable: true},
		{Name: "parsed_codec", Type: field.TypeString, Nullable: true},
		{Name: "transcoded_at", Type: field.TypeTime, Nullable: true},
		{Name: "size_before", Type: field.TypeInt64, Nullable: true},
		{Name: "episode_media_files", Type: field.TypeUint32, Nullable: true},
		{Name: "movie_media_files", Type: field.TypeUint32, Nullable: true},
	}
	// MediaFilesTable holds the schema information for the "media_files" table.
	MediaFilesTable = &schema.Table{
		Name:       "media_files",
		Columns:    MediaFilesColumns,
		PrimaryKey: []*schema.Column{MediaFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_files_episodes_media_files",
				Columns:    []*schema.Column{MediaFilesColumns[28]},
				RefColumns: []*schema.Column{EpisodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "media_files_movies_media_files",
				Columns:    []*schema.Column{MediaFilesColumns[29]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mediafile_episode_media_files",
				Unique:  false,
				Columns: []*schema.Column{MediaFilesColumns[28]},
			},
			{
				Name:    "mediafile_movie_media_files",
				Unique:  false,
				Columns: []*schema.Column{MediaFilesColumns[29]},
			},
			{
				Name:    "mediafile_probed_at",
				Unique:  false,
				Columns: []*schema.Column{MediaFilesColumns[22]},
				Annotation: &entsql.IndexAnnotation{
					Where: "probed_at IS NULL",
				},
			},
		},
	}
	// MoviesColumns holds the columns for the "movies" table.
	MoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "original_title", Type: field.TypeString},
		{Name: "year", Type: field.TypeUint16},
		{Name: "overview", Type: field.TypeString, Nullable: true},
		{Name: "runtime", Type: field.TypeUint16, Nullable: true, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"wanted", "downloading", "importing", "available", "failed"}, Default: "wanted"},
		{Name: "monitored", Type: field.TypeBool, Default: true},
		{Name: "tmdb_id", Type: field.TypeUint32, Unique: true},
		{Name: "last_search_at", Type: field.TypeTime, Nullable: true},
		{Name: "release_date", Type: field.TypeTime, Nullable: true},
		{Name: "digital_release_date", Type: field.TypeTime, Nullable: true},
		{Name: "grab_failures", Type: field.TypeUint8, Default: 0},
		{Name: "failure_reason", Type: field.TypeString, Nullable: true},
		{Name: "quality_profile", Type: field.TypeString, Nullable: true},
		{Name: "rating", Type: field.TypeFloat64, Nullable: true, Default: 0},
		{Name: "genres", Type: field.TypeJSON, Nullable: true},
		{Name: "aliases", Type: field.TypeJSON, Nullable: true},
		{Name: "last_refreshed_at", Type: field.TypeTime, Nullable: true},
	}
	// MoviesTable holds the schema information for the "movies" table.
	MoviesTable = &schema.Table{
		Name:       "movies",
		Columns:    MoviesColumns,
		PrimaryKey: []*schema.Column{MoviesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "movie_digital_release_date",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[13]},
			},
			{
				Name:    "movie_status",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[8]},
			},
			{
				Name:    "movie_create_time",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[1]},
			},
		},
	}
	// OidcIdentitiesColumns holds the columns for the "oidc_identities" table.
	OidcIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "provider", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "user_oidc_identities", Type: field.TypeUint32},
	}
	// OidcIdentitiesTable holds the schema information for the "oidc_identities" table.
	OidcIdentitiesTable = &schema.Table{
		Name:       "oidc_identities",
		Columns:    OidcIdentitiesColumns,
		PrimaryKey: []*schema.Column{OidcIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "oidc_identities_users_oidc_identities",
				Columns:    []*schema.Column{OidcIdentitiesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "oidcidentity_provider_subject",
				Unique:  true,
				Columns: []*schema.Column{OidcIdentitiesColumns[3], OidcIdentitiesColumns[4]},
			},
			{
				Name:    "oidcidentity_user_oidc_identities",
				Unique:  false,
				Columns: []*schema.Column{OidcIdentitiesColumns[6]},
			},
		},
	}
	// PersonsColumns holds the columns for the "persons" table.
	PersonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "tmdb_id", Type: field.TypeUint32, Nullable: true, Default: 0},
		{Name: "tvdb_id", Type: field.TypeUint32, Nullable: true, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "profile_url", Type: field.TypeString, Nullable: true},
		{Name: "biography", Type: field.TypeString, Nullable: true},
		{Name: "known_for", Type: field.TypeString, Nullable: true},
		{Name: "birthday", Type: field.TypeString, Nullable: true},
		{Name: "deathday", Type: field.TypeString, Nullable: true},
		{Name: "place_of_birth", Type: field.TypeString, Nullable: true},
		{Name: "imdb_id", Type: field.TypeString, Nullable: true},
		{Name: "instagram_id", Type: field.TypeString, Nullable: true},
		{Name: "twitter_id", Type: field.TypeString, Nullable: true},
		{Name: "details_fetched_at", Type: field.TypeTime, Nullable: true},
	}
	// PersonsTable holds the schema information for the "persons" table.
	PersonsTable = &schema.Table{
		Name:       "persons",
		Columns:    PersonsColumns,
		PrimaryKey: []*schema.Column{PersonsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "person_tmdb_id",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[3]},
			},
			{
				Name:    "person_tvdb_id",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[4]},
			},
			{
				Name:    "person_name",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[5]},
			},
		},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "media_type", Type: field.TypeEnum, Enums: []string{"movie", "tvshow"}},
		{Name: "media_id", Type: field.TypeUint32},
		{Name: "title", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "denied", "available"}, Default: "pending"},
		{Name: "reason", Type: field.TypeString, Nullable: true},
		{Name: "quality_profile", Type: field.TypeString, Nullable: true},
		{Name: "request_approved_by", Type: field.TypeUint32, Nullable: true},
		{Name: "user_requests", Type: field.TypeUint32},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_users_approved_by",
				Columns:    []*schema.Column{RequestsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_users_requests",
				Columns:    []*schema.Column{RequestsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_media_type_media_id",
				Unique:  true,
				Columns: []*schema.Column{RequestsColumns[3], RequestsColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status IN ('pending', 'approved', 'available')",
				},
			},
			{
				Name:    "request_user_requests",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[10]},
			},
			{
				Name:    "request_request_approved_by",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[9]},
			},
		},
	}
	// ScheduledJobsColumns holds the columns for the "scheduled_jobs" table.
	ScheduledJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "paused", Type: field.TypeBool, Default: false},
		{Name: "last_finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_status", Type: field.TypeEnum, Enums: []string{"never", "success", "error", "skipped"}, Default: "never"},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "last_duration_ms", Type: field.TypeUint32, Default: 0},
	}
	// ScheduledJobsTable holds the schema information for the "scheduled_jobs" table.
	ScheduledJobsTable = &schema.Table{
		Name:       "scheduled_jobs",
		Columns:    ScheduledJobsColumns,
		PrimaryKey: []*schema.Column{ScheduledJobsColumns[0]},
	}
	// SeasonsColumns holds the columns for the "seasons" table.
	SeasonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "number", Type: field.TypeUint16},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "monitored", Type: field.TypeBool, Default: true},
		{Name: "tv_show_seasons", Type: field.TypeUint32},
	}
	// SeasonsTable holds the schema information for the "seasons" table.
	SeasonsTable = &schema.Table{
		Name:       "seasons",
		Columns:    SeasonsColumns,
		PrimaryKey: []*schema.Column{SeasonsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "seasons_tv_shows_seasons",
				Columns:    []*schema.Column{SeasonsColumns[6]},
				RefColumns: []*schema.Column{TvShowsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "season_tv_show_seasons",
				Unique:  false,
				Columns: []*schema.Column{SeasonsColumns[6]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "jti", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "user_sessions", Type: field.TypeUint32},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_sessions",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[9]},
			},
		},
	}
	// TvShowsColumns holds the columns for the "tv_shows" table.
	TvShowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "original_title", Type: field.TypeString, Nullable: true},
		{Name: "year", Type: field.TypeUint16},
		{Name: "first_aired", Type: field.TypeTime, Nullable: true},
		{Name: "overview", Type: field.TypeString, Nullable: true},
		{Name: "series_status", Type: field.TypeEnum, Enums: []string{"continuing", "ended"}, Default: "continuing"},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"standard", "anime", "daily"}, Default: "standard"},
		{Name: "monitored", Type: field.TypeBool, Default: true},
		{Name: "tvdb_id", Type: field.TypeUint32, Unique: true},
		{Name: "poster_path", Type: field.TypeString, Nullable: true},
		{Name: "network", Type: field.TypeString, Nullable: true},
		{Name: "creator", Type: field.TypeString, Nullable: true},
		{Name: "runtime", Type: field.TypeUint16, Nullable: true, Default: 0},
		{Name: "rating", Type: field.TypeFloat64, Nullable: true, Default: 0},
		{Name: "genres", Type: field.TypeJSON, Nullable: true},
		{Name: "aliases", Type: field.TypeJSON, Nullable: true},
		{Name: "last_refreshed_at", Type: field.TypeTime, Nullable: true},
		{Name: "quality_profile", Type: field.TypeString, Nullable: true},
	}
	// TvShowsTable holds the schema information for the "tv_shows" table.
	TvShowsTable = &schema.Table{
		Name:       "tv_shows",
		Columns:    TvShowsColumns,
		PrimaryKey: []*schema.Column{TvShowsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tvshow_create_time",
				Unique:  false,
				Columns: []*schema.Column{TvShowsColumns[1]},
			},
			{
				Name:    "tvshow_series_status",
				Unique:  false,
				Columns: []*schema.Column{TvShowsColumns[8]},
			},
		},
	}
	// TorrentSessionsColumns holds the columns for the "torrent_sessions" table.
	TorrentSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "info_hash", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "save_path", Type: field.TypeString},
		{Name: "source_magnet", Type: field.TypeString, Nullable: true},
		{Name: "source_torrent", Type: field.TypeBytes, Nullable: true},
		{Name: "paused", Type: field.TypeBool, Default: false},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "seed_stopped", Type: field.TypeBool, Default: false},
		{Name: "uploaded", Type: field.TypeInt64, Default: 0},
		{Name: "wanted_files", Type: field.TypeJSON, Nullable: true},
		{Name: "selection_mode", Type: field.TypeEnum, Enums: []string{"all", "pending", "explicit"}, Default: "all"},
	}
	// TorrentSessionsTable holds the schema information for the "torrent_sessions" table.
	TorrentSessionsTable = &schema.Table{
		Name:       "torrent_sessions",
		Columns:    TorrentSessionsColumns,
		PrimaryKey: []*schema.Column{TorrentSessionsColumns[0]},
	}
	// TranscodeJobsColumns holds the columns for the "transcode_jobs" table.
	TranscodeJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"queued", "running", "succeeded", "failed", "canceled", "rejected"}, Default: "queued"},
		{Name: "attempts", Type: field.TypeUint8, Default: 0},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "size_before", Type: field.TypeInt64, Nullable: true},
		{Name: "size_after", Type: field.TypeInt64, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "deferred_until", Type: field.TypeTime, Nullable: true},
		{Name: "media_file_transcode_jobs", Type: field.TypeUint32},
	}
	// TranscodeJobsTable holds the schema information for the "transcode_jobs" table.
	TranscodeJobsTable = &schema.Table{
		Name:       "transcode_jobs",
		Columns:    TranscodeJobsColumns,
		PrimaryKey: []*schema.Column{TranscodeJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transcode_jobs_media_files_transcode_jobs",
				Columns:    []*schema.Column{TranscodeJobsColumns[11]},
				RefColumns: []*schema.Column{MediaFilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transcodejob_status",
				Unique:  false,
				Columns: []*schema.Column{TranscodeJobsColumns[3]},
			},
			{
				Name:    "transcodejob_media_file_transcode_jobs",
				Unique:  false,
				Columns: []*schema.Column{TranscodeJobsColumns[11]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member", "request_only"}, Default: "member"},
		{Name: "auth_method", Type: field.TypeEnum, Enums: []string{"local", "oidc", "both"}, Default: "local"},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "failed_login_count", Type: field.TypeUint8, Default: 0},
		{Name: "last_failed_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// DownloadRecordEpisodesColumns holds the columns for the "download_record_episodes" table.
	DownloadRecordEpisodesColumns = []*schema.Column{
		{Name: "episode_id", Type: field.TypeUint32},
		{Name: "download_record_id", Type: field.TypeUint32},
	}
	// DownloadRecordEpisodesTable holds the schema information for the "download_record_episodes" table.
	DownloadRecordEpisodesTable = &schema.Table{
		Name:       "download_record_episodes",
		Columns:    DownloadRecordEpisodesColumns,
		PrimaryKey: []*schema.Column{DownloadRecordEpisodesColumns[0], DownloadRecordEpisodesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "download_record_episodes_episode_id",
				Columns:    []*schema.Column{DownloadRecordEpisodesColumns[0]},
				RefColumns: []*schema.Column{EpisodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "download_record_episodes_download_record_id",
				Columns:    []*schema.Column{DownloadRecordEpisodesColumns[1]},
				RefColumns: []*schema.Column{DownloadRecordsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		CreditsTable,
		DownloadRecordsTable,
		EpisodesTable,
		ImportScansTable,
		ImportScanFilesTable,
		ImportScanShowsTable,
		InvitesTable,
		MediaEventsTable,
		MediaFilesTable,
		MoviesTable,
		OidcIdentitiesTable,
		PersonsTable,
		RequestsTable,
		ScheduledJobsTable,
		SeasonsTable,
		SessionsTable,
		TvShowsTable,
		TorrentSessionsTable,
		TranscodeJobsTable,
		UsersTable,
		DownloadRecordEpisodesTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = UsersTable
	CreditsTable.ForeignKeys[0].RefTable = MoviesTable
	CreditsTable.ForeignKeys[1].RefTable = PersonsTable
	CreditsTable.ForeignKeys[2].RefTable = TvShowsTable
	DownloadRecordsTable.ForeignKeys[0].RefTable = EpisodesTable
	DownloadRecordsTable.ForeignKeys[1].RefTable = MoviesTable
	EpisodesTable.ForeignKeys[0].RefTable = SeasonsTable
	ImportScanFilesTable.ForeignKeys[0].RefTable = ImportScansTable
	ImportScanShowsTable.ForeignKeys[0].RefTable = ImportScansTable
	InvitesTable.ForeignKeys[0].RefTable = UsersTable
	InvitesTable.ForeignKeys[1].RefTable = UsersTable
	MediaEventsTable.ForeignKeys[0].RefTable = EpisodesTable
	MediaEventsTable.ForeignKeys[1].RefTable = MoviesTable
	MediaEventsTable.ForeignKeys[2].RefTable = TvShowsTable
	MediaFilesTable.ForeignKeys[0].RefTable = EpisodesTable
	MediaFilesTable.ForeignKeys[1].RefTable = MoviesTable
	OidcIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
	RequestsTable.ForeignKeys[0].RefTable = UsersTable
	RequestsTable.ForeignKeys[1].RefTable = UsersTable
	SeasonsTable.ForeignKeys[0].RefTable = TvShowsTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	TranscodeJobsTable.ForeignKeys[0].RefTable = MediaFilesTable
	DownloadRecordEpisodesTable.ForeignKeys[0].RefTable = EpisodesTable
	DownloadRecordEpisodesTable.ForeignKeys[1].RefTable = DownloadRecordsTable
}
