// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datahearth/streamline/ent/downloadrecord"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/movie"
	"github.com/datahearth/streamline/ent/schema"
)

// DownloadRecord is the model entity for the DownloadRecord schema.
type DownloadRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality string `json:"quality,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// Status holds the value of the "status" field.
	Status downloadrecord.Status `json:"status,omitempty"`
	// TorrentHash holds the value of the "torrent_hash" field.
	TorrentHash string `json:"torrent_hash,omitempty"`
	// ReleaseGroup holds the value of the "release_group" field.
	ReleaseGroup string `json:"release_group,omitempty"`
	// SavePath holds the value of the "save_path" field.
	SavePath string `json:"save_path,omitempty"`
	// ImportAttempts holds the value of the "import_attempts" field.
	ImportAttempts uint8 `json:"import_attempts,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason string `json:"failure_reason,omitempty"`
	// ImportedAt holds the value of the "imported_at" field.
	ImportedAt *time.Time `json:"imported_at,omitempty"`
	// IndexerName holds the value of the "indexer_name" field.
	IndexerName string `json:"indexer_name,omitempty"`
	// DownloadClientName holds the value of the "download_client_name" field.
	DownloadClientName string `json:"download_client_name,omitempty"`
	// ReplaceMode holds the value of the "replace_mode" field.
	ReplaceMode downloadrecord.ReplaceMode `json:"replace_mode,omitempty"`
	// HoldReasons holds the value of the "hold_reasons" field.
	HoldReasons []schema.HoldReason `json:"hold_reasons,omitempty"`
	// VerificationBypassed holds the value of the "verification_bypassed" field.
	VerificationBypassed bool `json:"verification_bypassed,omitempty"`
	// SelectedFiles holds the value of the "selected_files" field.
	SelectedFiles []int `json:"selected_files,omitempty"`
	// SelectedBytes holds the value of the "selected_bytes" field.
	SelectedBytes int64 `json:"selected_bytes,omitempty"`
	// SelectionState holds the value of the "selection_state" field.
	SelectionState downloadrecord.SelectionState `json:"selection_state,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DownloadRecordQuery when eager-loading is set.
	Edges                    DownloadRecordEdges `json:"edges"`
	episode_download_records *uint32
	movie_download_records   *uint32
	selectValues             sql.SelectValues
}

// DownloadRecordEdges holds the relations/edges for other nodes in the graph.
type DownloadRecordEdges struct {
	// Movie holds the value of the movie edge.
	Movie *Movie `json:"movie,omitempty"`
	// AnchorEpisode holds the value of the anchor_episode edge.
	AnchorEpisode *Episode `json:"anchor_episode,omitempty"`
	// Episodes holds the value of the episodes edge.
	Episodes []*Episode `json:"episodes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// MovieOrErr returns the Movie value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DownloadRecordEdges) MovieOrErr() (*Movie, error) {
	if e.Movie != nil {
		return e.Movie, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: movie.Label}
	}
	return nil, &NotLoadedError{edge: "movie"}
}

// AnchorEpisodeOrErr returns the AnchorEpisode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DownloadRecordEdges) AnchorEpisodeOrErr() (*Episode, error) {
	if e.AnchorEpisode != nil {
		return e.AnchorEpisode, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: episode.Label}
	}
	return nil, &NotLoadedError{edge: "anchor_episode"}
}

// EpisodesOrErr returns the Episodes value or an error if the edge
// was not loaded in eager-loading.
func (e DownloadRecordEdges) EpisodesOrErr() ([]*Episode, error) {
	if e.loadedTypes[2] {
		return e.Episodes, nil
	}
	return nil, &NotLoadedError{edge: "episodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DownloadRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case downloadrecord.FieldHoldReasons, downloadrecord.FieldSelectedFiles:
			values[i] = new([]byte)
		case downloadrecord.FieldVerificationBypassed:
			values[i] = new(sql.NullBool)
		case downloadrecord.FieldID, downloadrecord.FieldSize, downloadrecord.FieldImportAttempts, downloadrecord.FieldSelectedBytes:
			values[i] = new(sql.NullInt64)
		case downloadrecord.FieldTitle, downloadrecord.FieldQuality, downloadrecord.FieldStatus, downloadrecord.FieldTorrentHash, downloadrecord.FieldReleaseGroup, downloadrecord.FieldSavePath, downloadrecord.FieldFailureReason, downloadrecord.FieldIndexerName, downloadrecord.FieldDownloadClientName, downloadrecord.FieldReplaceMode, downloadrecord.FieldSelectionState:
			values[i] = new(sql.NullString)
		case downloadrecord.FieldCreateTime, downloadrecord.FieldUpdateTime, downloadrecord.FieldImportedAt:
			values[i] = new(sql.NullTime)
		case downloadrecord.ForeignKeys[0]: // episode_download_records
			values[i] = new(sql.NullInt64)
		case downloadrecord.ForeignKeys[1]: // movie_download_records
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DownloadRecord fields.
func (_m *DownloadRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case downloadrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case downloadrecord.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case downloadrecord.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case downloadrecord.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case downloadrecord.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = value.String
			}
		case downloadrecord.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case downloadrecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = downloadrecord.Status(value.String)
			}
		case downloadrecord.FieldTorrentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field torrent_hash", values[i])
			} else if value.Valid {
				_m.TorrentHash = value.String
			}
		case downloadrecord.FieldReleaseGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_group", values[i])
			} else if value.Valid {
				_m.ReleaseGroup = value.String
			}
		case downloadrecord.FieldSavePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field save_path", values[i])
			} else if value.Valid {
				_m.SavePath = value.String
			}
		case downloadrecord.FieldImportAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field import_attempts", values[i])
			} else if value.Valid {
				_m.ImportAttempts = uint8(value.Int64)
			}
		case downloadrecord.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = value.String
			}
		case downloadrecord.FieldImportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field imported_at", values[i])
			} else if value.Valid {
				_m.ImportedAt = new(time.Time)
				*_m.ImportedAt = value.Time
			}
		case downloadrecord.FieldIndexerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field indexer_name", values[i])
			} else if value.Valid {
				_m.IndexerName = value.String
			}
		case downloadrecord.FieldDownloadClientName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field download_client_name", values[i])
			} else if value.Valid {
				_m.DownloadClientName = value.String
			}
		case downloadrecord.FieldReplaceMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replace_mode", values[i])
			} else if value.Valid {
				_m.ReplaceMode = downloadrecord.ReplaceMode(value.String)
			}
		case downloadrecord.FieldHoldReasons:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field hold_reasons", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.HoldReasons); err != nil {
					return fmt.Errorf("unmarshal field hold_reasons: %w", err)
				}
			}
		case downloadrecord.FieldVerificationBypassed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verification_bypassed", values[i])
			} else if value.Valid {
				_m.VerificationBypassed = value.Bool
			}
		case downloadrecord.FieldSelectedFiles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_files", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedFiles); err != nil {
					return fmt.Errorf("unmarshal field selected_files: %w", err)
				}
			}
		case downloadrecord.FieldSelectedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field selected_bytes", values[i])
			} else if value.Valid {
				_m.SelectedBytes = value.Int64
			}
		case downloadrecord.FieldSelectionState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selection_state", values[i])
			} else if value.Valid {
				_m.SelectionState = downloadrecord.SelectionState(value.String)
			}
		case downloadrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field episode_download_records", value)
			} else if value.Valid {
				_m.episode_download_records = new(uint32)
				*_m.episode_download_records = uint32(value.Int64)
			}
		case downloadrecord.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field movie_download_records", value)
			} else if value.Valid {
				_m.movie_download_records = new(uint32)
				*_m.movie_download_records = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DownloadRecord.
// This includes values selected through modifiers, order, etc.
func (_m *DownloadRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMovie queries the "movie" edge of the DownloadRecord entity.
func (_m *DownloadRecord) QueryMovie() *MovieQuery {
	return NewDownloadRecordClient(_m.config).QueryMovie(_m)
}

// QueryAnchorEpisode queries the "anchor_episode" edge of the DownloadRecord entity.
func (_m *DownloadRecord) QueryAnchorEpisode() *EpisodeQuery {
	return NewDownloadRecordClient(_m.config).QueryAnchorEpisode(_m)
}

// QueryEpisodes queries the "episodes" edge of the DownloadRecord entity.
func (_m *DownloadRecord) QueryEpisodes() *EpisodeQuery {
	return NewDownloadRecordClient(_m.config).QueryEpisodes(_m)
}

// Update returns a builder for updating this DownloadRecord.
// Note that you need to call DownloadRecord.Unwrap() before calling this method if this DownloadRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DownloadRecord) Update() *DownloadRecordUpdateOne {
	return NewDownloadRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DownloadRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DownloadRecord) Unwrap() *DownloadRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DownloadRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DownloadRecord) String() string {
	var builder strings.Builder
	builder.WriteString("DownloadRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("quality=")
	builder.WriteString(_m.Quality)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("torrent_hash=")
	builder.WriteString(_m.TorrentHash)
	builder.WriteString(", ")
	builder.WriteString("release_group=")
	builder.WriteString(_m.ReleaseGroup)
	builder.WriteString(", ")
	builder.WriteString("save_path=")
	builder.WriteString(_m.SavePath)
	builder.WriteString(", ")
	builder.WriteString("import_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImportAttempts))
	builder.WriteString(", ")
	builder.WriteString("failure_reason=")
	builder.WriteString(_m.FailureReason)
	builder.WriteString(", ")
	if v := _m.ImportedAt; v != nil {
		builder.WriteString("imported_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("indexer_name=")
	builder.WriteString(_m.IndexerName)
	builder.WriteString(", ")
	builder.WriteString("download_client_name=")
	builder.WriteString(_m.DownloadClientName)
	builder.WriteString(", ")
	builder.WriteString("replace_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReplaceMode))
	builder.WriteString(", ")
	builder.WriteString("hold_reasons=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoldReasons))
	builder.WriteString(", ")
	builder.WriteString("verification_bypassed=")
	builder.WriteString(fmt.Sprintf("%v", _m.VerificationBypassed))
	builder.WriteString(", ")
	builder.WriteString("selected_files=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedFiles))
	builder.WriteString(", ")
	builder.WriteString("selected_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedBytes))
	builder.WriteString(", ")
	builder.WriteString("selection_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectionState))
	builder.WriteByte(')')
	return builder.String()
}

// DownloadRecords is a parsable slice of DownloadRecord.
type DownloadRecords []*DownloadRecord
