// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/downloadrecord"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/movie"
	"github.com/datahearth/streamline/ent/schema"
)

// DownloadRecordCreate is the builder for creating a DownloadRecord entity.
type DownloadRecordCreate struct {
	config
	mutation *DownloadRecordMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *DownloadRecordCreate) SetCreateTime(v time.Time) *DownloadRecordCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableCreateTime(v *time.Time) *DownloadRecordCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *DownloadRecordCreate) SetUpdateTime(v time.Time) *DownloadRecordCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableUpdateTime(v *time.Time) *DownloadRecordCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *DownloadRecordCreate) SetTitle(v string) *DownloadRecordCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetQuality sets the "quality" field.
func (_c *DownloadRecordCreate) SetQuality(v string) *DownloadRecordCreate {
	_c.mutation.SetQuality(v)
	return _c
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableQuality(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetQuality(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *DownloadRecordCreate) SetSize(v int64) *DownloadRecordCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableSize(v *int64) *DownloadRecordCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DownloadRecordCreate) SetStatus(v downloadrecord.Status) *DownloadRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableStatus(v *downloadrecord.Status) *DownloadRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTorrentHash sets the "torrent_hash" field.
func (_c *DownloadRecordCreate) SetTorrentHash(v string) *DownloadRecordCreate {
	_c.mutation.SetTorrentHash(v)
	return _c
}

// SetNillableTorrentHash sets the "torrent_hash" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableTorrentHash(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetTorrentHash(*v)
	}
	return _c
}

// SetReleaseGroup sets the "release_group" field.
func (_c *DownloadRecordCreate) SetReleaseGroup(v string) *DownloadRecordCreate {
	_c.mutation.SetReleaseGroup(v)
	return _c
}

// SetNillableReleaseGroup sets the "release_group" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableReleaseGroup(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetReleaseGroup(*v)
	}
	return _c
}

// SetSavePath sets the "save_path" field.
func (_c *DownloadRecordCreate) SetSavePath(v string) *DownloadRecordCreate {
	_c.mutation.SetSavePath(v)
	return _c
}

// SetNillableSavePath sets the "save_path" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableSavePath(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetSavePath(*v)
	}
	return _c
}

// SetImportAttempts sets the "import_attempts" field.
func (_c *DownloadRecordCreate) SetImportAttempts(v uint8) *DownloadRecordCreate {
	_c.mutation.SetImportAttempts(v)
	return _c
}

// SetNillableImportAttempts sets the "import_attempts" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableImportAttempts(v *uint8) *DownloadRecordCreate {
	if v != nil {
		_c.SetImportAttempts(*v)
	}
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *DownloadRecordCreate) SetFailureReason(v string) *DownloadRecordCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableFailureReason(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetImportedAt sets the "imported_at" field.
func (_c *DownloadRecordCreate) SetImportedAt(v time.Time) *DownloadRecordCreate {
	_c.mutation.SetImportedAt(v)
	return _c
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableImportedAt(v *time.Time) *DownloadRecordCreate {
	if v != nil {
		_c.SetImportedAt(*v)
	}
	return _c
}

// SetIndexerName sets the "indexer_name" field.
func (_c *DownloadRecordCreate) SetIndexerName(v string) *DownloadRecordCreate {
	_c.mutation.SetIndexerName(v)
	return _c
}

// SetNillableIndexerName sets the "indexer_name" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableIndexerName(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetIndexerName(*v)
	}
	return _c
}

// SetDownloadClientName sets the "download_client_name" field.
func (_c *DownloadRecordCreate) SetDownloadClientName(v string) *DownloadRecordCreate {
	_c.mutation.SetDownloadClientName(v)
	return _c
}

// SetNillableDownloadClientName sets the "download_client_name" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableDownloadClientName(v *string) *DownloadRecordCreate {
	if v != nil {
		_c.SetDownloadClientName(*v)
	}
	return _c
}

// SetReplaceMode sets the "replace_mode" field.
func (_c *DownloadRecordCreate) SetReplaceMode(v downloadrecord.ReplaceMode) *DownloadRecordCreate {
	_c.mutation.SetReplaceMode(v)
	return _c
}

// SetNillableReplaceMode sets the "replace_mode" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableReplaceMode(v *downloadrecord.ReplaceMode) *DownloadRecordCreate {
	if v != nil {
		_c.SetReplaceMode(*v)
	}
	return _c
}

// SetHoldReasons sets the "hold_reasons" field.
func (_c *DownloadRecordCreate) SetHoldReasons(v []schema.HoldReason) *DownloadRecordCreate {
	_c.mutation.SetHoldReasons(v)
	return _c
}

// SetVerificationBypassed sets the "verification_bypassed" field.
func (_c *DownloadRecordCreate) SetVerificationBypassed(v bool) *DownloadRecordCreate {
	_c.mutation.SetVerificationBypassed(v)
	return _c
}

// SetNillableVerificationBypassed sets the "verification_bypassed" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableVerificationBypassed(v *bool) *DownloadRecordCreate {
	if v != nil {
		_c.SetVerificationBypassed(*v)
	}
	return _c
}

// SetSelectedFiles sets the "selected_files" field.
func (_c *DownloadRecordCreate) SetSelectedFiles(v []int) *DownloadRecordCreate {
	_c.mutation.SetSelectedFiles(v)
	return _c
}

// SetSelectedBytes sets the "selected_bytes" field.
func (_c *DownloadRecordCreate) SetSelectedBytes(v int64) *DownloadRecordCreate {
	_c.mutation.SetSelectedBytes(v)
	return _c
}

// SetNillableSelectedBytes sets the "selected_bytes" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableSelectedBytes(v *int64) *DownloadRecordCreate {
	if v != nil {
		_c.SetSelectedBytes(*v)
	}
	return _c
}

// SetSelectionState sets the "selection_state" field.
func (_c *DownloadRecordCreate) SetSelectionState(v downloadrecord.SelectionState) *DownloadRecordCreate {
	_c.mutation.SetSelectionState(v)
	return _c
}

// SetNillableSelectionState sets the "selection_state" field if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableSelectionState(v *downloadrecord.SelectionState) *DownloadRecordCreate {
	if v != nil {
		_c.SetSelectionState(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DownloadRecordCreate) SetID(v uint32) *DownloadRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetMovieID sets the "movie" edge to the Movie entity by ID.
func (_c *DownloadRecordCreate) SetMovieID(id uint32) *DownloadRecordCreate {
	_c.mutation.SetMovieID(id)
	return _c
}

// SetNillableMovieID sets the "movie" edge to the Movie entity by ID if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableMovieID(id *uint32) *DownloadRecordCreate {
	if id != nil {
		_c = _c.SetMovieID(*id)
	}
	return _c
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_c *DownloadRecordCreate) SetMovie(v *Movie) *DownloadRecordCreate {
	return _c.SetMovieID(v.ID)
}

// SetAnchorEpisodeID sets the "anchor_episode" edge to the Episode entity by ID.
func (_c *DownloadRecordCreate) SetAnchorEpisodeID(id uint32) *DownloadRecordCreate {
	_c.mutation.SetAnchorEpisodeID(id)
	return _c
}

// SetNillableAnchorEpisodeID sets the "anchor_episode" edge to the Episode entity by ID if the given value is not nil.
func (_c *DownloadRecordCreate) SetNillableAnchorEpisodeID(id *uint32) *DownloadRecordCreate {
	if id != nil {
		_c = _c.SetAnchorEpisodeID(*id)
	}
	return _c
}

// SetAnchorEpisode sets the "anchor_episode" edge to the Episode entity.
func (_c *DownloadRecordCreate) SetAnchorEpisode(v *Episode) *DownloadRecordCreate {
	return _c.SetAnchorEpisodeID(v.ID)
}

// AddEpisodeIDs adds the "episodes" edge to the Episode entity by IDs.
func (_c *DownloadRecordCreate) AddEpisodeIDs(ids ...uint32) *DownloadRecordCreate {
	_c.mutation.AddEpisodeIDs(ids...)
	return _c
}

// AddEpisodes adds the "episodes" edges to the Episode entity.
func (_c *DownloadRecordCreate) AddEpisodes(v ...*Episode) *DownloadRecordCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEpisodeIDs(ids...)
}

// Mutation returns the DownloadRecordMutation object of the builder.
func (_c *DownloadRecordCreate) Mutation() *DownloadRecordMutation {
	return _c.mutation
}

// Save creates the DownloadRecord in the database.
func (_c *DownloadRecordCreate) Save(ctx context.Context) (*DownloadRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DownloadRecordCreate) SaveX(ctx context.Context) *DownloadRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownloadRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownloadRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DownloadRecordCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := downloadrecord.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := downloadrecord.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := downloadrecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ImportAttempts(); !ok {
		v := downloadrecord.DefaultImportAttempts
		_c.mutation.SetImportAttempts(v)
	}
	if _, ok := _c.mutation.ReplaceMode(); !ok {
		v := downloadrecord.DefaultReplaceMode
		_c.mutation.SetReplaceMode(v)
	}
	if _, ok := _c.mutation.VerificationBypassed(); !ok {
		v := downloadrecord.DefaultVerificationBypassed
		_c.mutation.SetVerificationBypassed(v)
	}
	if _, ok := _c.mutation.SelectionState(); !ok {
		v := downloadrecord.DefaultSelectionState
		_c.mutation.SetSelectionState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DownloadRecordCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "DownloadRecord.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "DownloadRecord.update_time"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "DownloadRecord.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := downloadrecord.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DownloadRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := downloadrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImportAttempts(); !ok {
		return &ValidationError{Name: "import_attempts", err: errors.New(`ent: missing required field "DownloadRecord.import_attempts"`)}
	}
	if _, ok := _c.mutation.ReplaceMode(); !ok {
		return &ValidationError{Name: "replace_mode", err: errors.New(`ent: missing required field "DownloadRecord.replace_mode"`)}
	}
	if v, ok := _c.mutation.ReplaceMode(); ok {
		if err := downloadrecord.ReplaceModeValidator(v); err != nil {
			return &ValidationError{Name: "replace_mode", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.replace_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationBypassed(); !ok {
		return &ValidationError{Name: "verification_bypassed", err: errors.New(`ent: missing required field "DownloadRecord.verification_bypassed"`)}
	}
	if _, ok := _c.mutation.SelectionState(); !ok {
		return &ValidationError{Name: "selection_state", err: errors.New(`ent: missing required field "DownloadRecord.selection_state"`)}
	}
	if v, ok := _c.mutation.SelectionState(); ok {
		if err := downloadrecord.SelectionStateValidator(v); err != nil {
			return &ValidationError{Name: "selection_state", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.selection_state": %w`, err)}
		}
	}
	return nil
}

func (_c *DownloadRecordCreate) sqlSave(ctx context.Context) (*DownloadRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DownloadRecordCreate) createSpec() (*DownloadRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &DownloadRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(downloadrecord.Table, sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(downloadrecord.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(downloadrecord.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(downloadrecord.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Quality(); ok {
		_spec.SetField(downloadrecord.FieldQuality, field.TypeString, value)
		_node.Quality = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(downloadrecord.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(downloadrecord.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TorrentHash(); ok {
		_spec.SetField(downloadrecord.FieldTorrentHash, field.TypeString, value)
		_node.TorrentHash = value
	}
	if value, ok := _c.mutation.ReleaseGroup(); ok {
		_spec.SetField(downloadrecord.FieldReleaseGroup, field.TypeString, value)
		_node.ReleaseGroup = value
	}
	if value, ok := _c.mutation.SavePath(); ok {
		_spec.SetField(downloadrecord.FieldSavePath, field.TypeString, value)
		_node.SavePath = value
	}
	if value, ok := _c.mutation.ImportAttempts(); ok {
		_spec.SetField(downloadrecord.FieldImportAttempts, field.TypeUint8, value)
		_node.ImportAttempts = value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(downloadrecord.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = value
	}
	if value, ok := _c.mutation.ImportedAt(); ok {
		_spec.SetField(downloadrecord.FieldImportedAt, field.TypeTime, value)
		_node.ImportedAt = &value
	}
	if value, ok := _c.mutation.IndexerName(); ok {
		_spec.SetField(downloadrecord.FieldIndexerName, field.TypeString, value)
		_node.IndexerName = value
	}
	if value, ok := _c.mutation.DownloadClientName(); ok {
		_spec.SetField(downloadrecord.FieldDownloadClientName, field.TypeString, value)
		_node.DownloadClientName = value
	}
	if value, ok := _c.mutation.ReplaceMode(); ok {
		_spec.SetField(downloadrecord.FieldReplaceMode, field.TypeEnum, value)
		_node.ReplaceMode = value
	}
	if value, ok := _c.mutation.HoldReasons(); ok {
		_spec.SetField(downloadrecord.FieldHoldReasons, field.TypeJSON, value)
		_node.HoldReasons = value
	}
	if value, ok := _c.mutation.VerificationBypassed(); ok {
		_spec.SetField(downloadrecord.FieldVerificationBypassed, field.TypeBool, value)
		_node.VerificationBypassed = value
	}
	if value, ok := _c.mutation.SelectedFiles(); ok {
		_spec.SetField(downloadrecord.FieldSelectedFiles, field.TypeJSON, value)
		_node.SelectedFiles = value
	}
	if value, ok := _c.mutation.SelectedBytes(); ok {
		_spec.SetField(downloadrecord.FieldSelectedBytes, field.TypeInt64, value)
		_node.SelectedBytes = value
	}
	if value, ok := _c.mutation.SelectionState(); ok {
		_spec.SetField(downloadrecord.FieldSelectionState, field.TypeEnum, value)
		_node.SelectionState = value
	}
	if nodes := _c.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.MovieTable,
			Columns: []string{downloadrecord.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.movie_download_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnchorEpisodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.AnchorEpisodeTable,
			Columns: []string{downloadrecord.AnchorEpisodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.episode_download_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EpisodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   downloadrecord.EpisodesTable,
			Columns: downloadrecord.EpisodesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DownloadRecordCreateBulk is the builder for creating many DownloadRecord entities in bulk.
type DownloadRecordCreateBulk struct {
	config
	err      error
	builders []*DownloadRecordCreate
}

// Save creates the DownloadRecord entities in the database.
func (_c *DownloadRecordCreateBulk) Save(ctx context.Context) ([]*DownloadRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DownloadRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DownloadRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DownloadRecordCreateBulk) SaveX(ctx context.Context) []*DownloadRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownloadRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownloadRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
