// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/downloadrecord"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/mediaevent"
	"github.com/datahearth/streamline/ent/mediafile"
	"github.com/datahearth/streamline/ent/predicate"
	"github.com/datahearth/streamline/ent/season"
)

// EpisodeQuery is the builder for querying Episode entities.
type EpisodeQuery struct {
	config
	ctx                         *QueryContext
	order                       []episode.OrderOption
	inters                      []Interceptor
	predicates                  []predicate.Episode
	withSeason                  *SeasonQuery
	withDownloadRecords         *DownloadRecordQuery
	withAnchoredDownloadRecords *DownloadRecordQuery
	withMediaFiles              *MediaFileQuery
	withEvents                  *MediaEventQuery
	withFKs                     bool
	modifiers                   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EpisodeQuery builder.
func (_q *EpisodeQuery) Where(ps ...predicate.Episode) *EpisodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EpisodeQuery) Limit(limit int) *EpisodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EpisodeQuery) Offset(offset int) *EpisodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EpisodeQuery) Unique(unique bool) *EpisodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EpisodeQuery) Order(o ...episode.OrderOption) *EpisodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySeason chains the current query on the "season" edge.
func (_q *EpisodeQuery) QuerySeason() *SeasonQuery {
	query := (&SeasonClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(episode.Table, episode.FieldID, selector),
			sqlgraph.To(season.Table, season.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, episode.SeasonTable, episode.SeasonColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDownloadRecords chains the current query on the "download_records" edge.
func (_q *EpisodeQuery) QueryDownloadRecords() *DownloadRecordQuery {
	query := (&DownloadRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(episode.Table, episode.FieldID, selector),
			sqlgraph.To(downloadrecord.Table, downloadrecord.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, episode.DownloadRecordsTable, episode.DownloadRecordsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAnchoredDownloadRecords chains the current query on the "anchored_download_records" edge.
func (_q *EpisodeQuery) QueryAnchoredDownloadRecords() *DownloadRecordQuery {
	query := (&DownloadRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(episode.Table, episode.FieldID, selector),
			sqlgraph.To(downloadrecord.Table, downloadrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, episode.AnchoredDownloadRecordsTable, episode.AnchoredDownloadRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMediaFiles chains the current query on the "media_files" edge.
func (_q *EpisodeQuery) QueryMediaFiles() *MediaFileQuery {
	query := (&MediaFileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(episode.Table, episode.FieldID, selector),
			sqlgraph.To(mediafile.Table, mediafile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, episode.MediaFilesTable, episode.MediaFilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *EpisodeQuery) QueryEvents() *MediaEventQuery {
	query := (&MediaEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(episode.Table, episode.FieldID, selector),
			sqlgraph.To(mediaevent.Table, mediaevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, episode.EventsTable, episode.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Episode entity from the query.
// Returns a *NotFoundError when no Episode was found.
func (_q *EpisodeQuery) First(ctx context.Context) (*Episode, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{episode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EpisodeQuery) FirstX(ctx context.Context) *Episode {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Episode ID from the query.
// Returns a *NotFoundError when no Episode ID was found.
func (_q *EpisodeQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{episode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EpisodeQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Episode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Episode entity is found.
// Returns a *NotFoundError when no Episode entities are found.
func (_q *EpisodeQuery) Only(ctx context.Context) (*Episode, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{episode.Label}
	default:
		return nil, &NotSingularError{episode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EpisodeQuery) OnlyX(ctx context.Context) *Episode {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Episode ID in the query.
// Returns a *NotSingularError when more than one Episode ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EpisodeQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{episode.Label}
	default:
		err = &NotSingularError{episode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EpisodeQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Episodes.
func (_q *EpisodeQuery) All(ctx context.Context) ([]*Episode, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Episode, *EpisodeQuery]()
	return withInterceptors[[]*Episode](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EpisodeQuery) AllX(ctx context.Context) []*Episode {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Episode IDs.
func (_q *EpisodeQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(episode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EpisodeQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EpisodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EpisodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EpisodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EpisodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EpisodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EpisodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EpisodeQuery) Clone() *EpisodeQuery {
	if _q == nil {
		return nil
	}
	return &EpisodeQuery{
		config:                      _q.config,
		ctx:                         _q.ctx.Clone(),
		order:                       append([]episode.OrderOption{}, _q.order...),
		inters:                      append([]Interceptor{}, _q.inters...),
		predicates:                  append([]predicate.Episode{}, _q.predicates...),
		withSeason:                  _q.withSeason.Clone(),
		withDownloadRecords:         _q.withDownloadRecords.Clone(),
		withAnchoredDownloadRecords: _q.withAnchoredDownloadRecords.Clone(),
		withMediaFiles:              _q.withMediaFiles.Clone(),
		withEvents:                  _q.withEvents.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithSeason tells the query-builder to eager-load the nodes that are connected to
// the "season" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EpisodeQuery) WithSeason(opts ...func(*SeasonQuery)) *EpisodeQuery {
	query := (&SeasonClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSeason = query
	return _q
}

// WithDownloadRecords tells the query-builder to eager-load the nodes that are connected to
// the "download_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EpisodeQuery) WithDownloadRecords(opts ...func(*DownloadRecordQuery)) *EpisodeQuery {
	query := (&DownloadRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDownloadRecords = query
	return _q
}

// WithAnchoredDownloadRecords tells the query-builder to eager-load the nodes that are connected to
// the "anchored_download_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EpisodeQuery) WithAnchoredDownloadRecords(opts ...func(*DownloadRecordQuery)) *EpisodeQuery {
	query := (&DownloadRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAnchoredDownloadRecords = query
	return _q
}

// WithMediaFiles tells the query-builder to eager-load the nodes that are connected to
// the "media_files" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EpisodeQuery) WithMediaFiles(opts ...func(*MediaFileQuery)) *EpisodeQuery {
	query := (&MediaFileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMediaFiles = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EpisodeQuery) WithEvents(opts ...func(*MediaEventQuery)) *EpisodeQuery {
	query := (&MediaEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Episode.Query().
//		GroupBy(episode.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EpisodeQuery) GroupBy(field string, fields ...string) *EpisodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EpisodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = episode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Episode.Query().
//		Select(episode.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *EpisodeQuery) Select(fields ...string) *EpisodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EpisodeSelect{EpisodeQuery: _q}
	sbuild.label = episode.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EpisodeSelect configured with the given aggregations.
func (_q *EpisodeQuery) Aggregate(fns ...AggregateFunc) *EpisodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EpisodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !episode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EpisodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Episode, error) {
	var (
		nodes       = []*Episode{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withSeason != nil,
			_q.withDownloadRecords != nil,
			_q.withAnchoredDownloadRecords != nil,
			_q.withMediaFiles != nil,
			_q.withEvents != nil,
		}
	)
	if _q.withSeason != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, episode.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Episode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Episode{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSeason; query != nil {
		if err := _q.loadSeason(ctx, query, nodes, nil,
			func(n *Episode, e *Season) { n.Edges.Season = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDownloadRecords; query != nil {
		if err := _q.loadDownloadRecords(ctx, query, nodes,
			func(n *Episode) { n.Edges.DownloadRecords = []*DownloadRecord{} },
			func(n *Episode, e *DownloadRecord) { n.Edges.DownloadRecords = append(n.Edges.DownloadRecords, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAnchoredDownloadRecords; query != nil {
		if err := _q.loadAnchoredDownloadRecords(ctx, query, nodes,
			func(n *Episode) { n.Edges.AnchoredDownloadRecords = []*DownloadRecord{} },
			func(n *Episode, e *DownloadRecord) {
				n.Edges.AnchoredDownloadRecords = append(n.Edges.AnchoredDownloadRecords, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withMediaFiles; query != nil {
		if err := _q.loadMediaFiles(ctx, query, nodes,
			func(n *Episode) { n.Edges.MediaFiles = []*MediaFile{} },
			func(n *Episode, e *MediaFile) { n.Edges.MediaFiles = append(n.Edges.MediaFiles, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *Episode) { n.Edges.Events = []*MediaEvent{} },
			func(n *Episode, e *MediaEvent) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EpisodeQuery) loadSeason(ctx context.Context, query *SeasonQuery, nodes []*Episode, init func(*Episode), assign func(*Episode, *Season)) error {
	ids := make([]uint32, 0, len(nodes))
	nodeids := make(map[uint32][]*Episode)
	for i := range nodes {
		if nodes[i].season_episodes == nil {
			continue
		}
		fk := *nodes[i].season_episodes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(season.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "season_episodes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EpisodeQuery) loadDownloadRecords(ctx context.Context, query *DownloadRecordQuery, nodes []*Episode, init func(*Episode), assign func(*Episode, *DownloadRecord)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint32]*Episode)
	nids := make(map[uint32]map[*Episode]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(episode.DownloadRecordsTable)
		s.Join(joinT).On(s.C(downloadrecord.FieldID), joinT.C(episode.DownloadRecordsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(episode.DownloadRecordsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(episode.DownloadRecordsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint32(values[0].(*sql.NullInt64).Int64)
				inValue := uint32(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Episode]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*DownloadRecord](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "download_records" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *EpisodeQuery) loadAnchoredDownloadRecords(ctx context.Context, query *DownloadRecordQuery, nodes []*Episode, init func(*Episode), assign func(*Episode, *DownloadRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint32]*Episode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DownloadRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(episode.AnchoredDownloadRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.episode_download_records
		if fk == nil {
			return fmt.Errorf(`foreign-key "episode_download_records" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "episode_download_records" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EpisodeQuery) loadMediaFiles(ctx context.Context, query *MediaFileQuery, nodes []*Episode, init func(*Episode), assign func(*Episode, *MediaFile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint32]*Episode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MediaFile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(episode.MediaFilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.episode_media_files
		if fk == nil {
			return fmt.Errorf(`foreign-key "episode_media_files" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "episode_media_files" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EpisodeQuery) loadEvents(ctx context.Context, query *MediaEventQuery, nodes []*Episode, init func(*Episode), assign func(*Episode, *MediaEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint32]*Episode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MediaEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(episode.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.episode_events
		if fk == nil {
			return fmt.Errorf(`foreign-key "episode_events" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "episode_events" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EpisodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EpisodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, episode.FieldID)
		for i := range fields {
			if fields[i] != episode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EpisodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(episode.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = episode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *EpisodeQuery) Modify(modifiers ...func(s *sql.Selector)) *EpisodeSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// EpisodeGroupBy is the group-by builder for Episode entities.
type EpisodeGroupBy struct {
	selector
	build *EpisodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EpisodeGroupBy) Aggregate(fns ...AggregateFunc) *EpisodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EpisodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EpisodeQuery, *EpisodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EpisodeGroupBy) sqlScan(ctx context.Context, root *EpisodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EpisodeSelect is the builder for selecting fields of Episode entities.
type EpisodeSelect struct {
	*EpisodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EpisodeSelect) Aggregate(fns ...AggregateFunc) *EpisodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EpisodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EpisodeQuery, *EpisodeSelect](ctx, _s.EpisodeQuery, _s, _s.inters, v)
}

func (_s *EpisodeSelect) sqlScan(ctx context.Context, root *EpisodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *EpisodeSelect) Modify(modifiers ...func(s *sql.Selector)) *EpisodeSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
