// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/season"
)

// Episode is the model entity for the Episode schema.
type Episode struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Number holds the value of the "number" field.
	Number uint16 `json:"number,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Overview holds the value of the "overview" field.
	Overview string `json:"overview,omitempty"`
	// AirDate holds the value of the "air_date" field.
	AirDate time.Time `json:"air_date,omitempty"`
	// Monitored holds the value of the "monitored" field.
	Monitored bool `json:"monitored,omitempty"`
	// AbsoluteNumber holds the value of the "absolute_number" field.
	AbsoluteNumber uint16 `json:"absolute_number,omitempty"`
	// GrabFailures holds the value of the "grab_failures" field.
	GrabFailures uint8 `json:"grab_failures,omitempty"`
	// LastSearchAt holds the value of the "last_search_at" field.
	LastSearchAt *time.Time `json:"last_search_at,omitempty"`
	// Status holds the value of the "status" field.
	Status episode.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EpisodeQuery when eager-loading is set.
	Edges           EpisodeEdges `json:"edges"`
	season_episodes *uint32
	selectValues    sql.SelectValues
}

// EpisodeEdges holds the relations/edges for other nodes in the graph.
type EpisodeEdges struct {
	// Season holds the value of the season edge.
	Season *Season `json:"season,omitempty"`
	// DownloadRecords holds the value of the download_records edge.
	DownloadRecords []*DownloadRecord `json:"download_records,omitempty"`
	// AnchoredDownloadRecords holds the value of the anchored_download_records edge.
	AnchoredDownloadRecords []*DownloadRecord `json:"anchored_download_records,omitempty"`
	// MediaFiles holds the value of the media_files edge.
	MediaFiles []*MediaFile `json:"media_files,omitempty"`
	// Events holds the value of the events edge.
	Events []*MediaEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// SeasonOrErr returns the Season value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EpisodeEdges) SeasonOrErr() (*Season, error) {
	if e.Season != nil {
		return e.Season, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: season.Label}
	}
	return nil, &NotLoadedError{edge: "season"}
}

// DownloadRecordsOrErr returns the DownloadRecords value or an error if the edge
// was not loaded in eager-loading.
func (e EpisodeEdges) DownloadRecordsOrErr() ([]*DownloadRecord, error) {
	if e.loadedTypes[1] {
		return e.DownloadRecords, nil
	}
	return nil, &NotLoadedError{edge: "download_records"}
}

// AnchoredDownloadRecordsOrErr returns the AnchoredDownloadRecords value or an error if the edge
// was not loaded in eager-loading.
func (e EpisodeEdges) AnchoredDownloadRecordsOrErr() ([]*DownloadRecord, error) {
	if e.loadedTypes[2] {
		return e.AnchoredDownloadRecords, nil
	}
	return nil, &NotLoadedError{edge: "anchored_download_records"}
}

// MediaFilesOrErr returns the MediaFiles value or an error if the edge
// was not loaded in eager-loading.
func (e EpisodeEdges) MediaFilesOrErr() ([]*MediaFile, error) {
	if e.loadedTypes[3] {
		return e.MediaFiles, nil
	}
	return nil, &NotLoadedError{edge: "media_files"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e EpisodeEdges) EventsOrErr() ([]*MediaEvent, error) {
	if e.loadedTypes[4] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Episode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case episode.FieldMonitored:
			values[i] = new(sql.NullBool)
		case episode.FieldID, episode.FieldNumber, episode.FieldAbsoluteNumber, episode.FieldGrabFailures:
			values[i] = new(sql.NullInt64)
		case episode.FieldTitle, episode.FieldOverview, episode.FieldStatus:
			values[i] = new(sql.NullString)
		case episode.FieldCreateTime, episode.FieldUpdateTime, episode.FieldAirDate, episode.FieldLastSearchAt:
			values[i] = new(sql.NullTime)
		case episode.ForeignKeys[0]: // season_episodes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Episode fields.
func (_m *Episode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case episode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case episode.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case episode.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case episode.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				_m.Number = uint16(value.Int64)
			}
		case episode.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case episode.FieldOverview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overview", values[i])
			} else if value.Valid {
				_m.Overview = value.String
			}
		case episode.FieldAirDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field air_date", values[i])
			} else if value.Valid {
				_m.AirDate = value.Time
			}
		case episode.FieldMonitored:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field monitored", values[i])
			} else if value.Valid {
				_m.Monitored = value.Bool
			}
		case episode.FieldAbsoluteNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field absolute_number", values[i])
			} else if value.Valid {
				_m.AbsoluteNumber = uint16(value.Int64)
			}
		case episode.FieldGrabFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grab_failures", values[i])
			} else if value.Valid {
				_m.GrabFailures = uint8(value.Int64)
			}
		case episode.FieldLastSearchAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_search_at", values[i])
			} else if value.Valid {
				_m.LastSearchAt = new(time.Time)
				*_m.LastSearchAt = value.Time
			}
		case episode.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = episode.Status(value.String)
			}
		case episode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field season_episodes", value)
			} else if value.Valid {
				_m.season_episodes = new(uint32)
				*_m.season_episodes = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Episode.
// This includes values selected through modifiers, order, etc.
func (_m *Episode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySeason queries the "season" edge of the Episode entity.
func (_m *Episode) QuerySeason() *SeasonQuery {
	return NewEpisodeClient(_m.config).QuerySeason(_m)
}

// QueryDownloadRecords queries the "download_records" edge of the Episode entity.
func (_m *Episode) QueryDownloadRecords() *DownloadRecordQuery {
	return NewEpisodeClient(_m.config).QueryDownloadRecords(_m)
}

// QueryAnchoredDownloadRecords queries the "anchored_download_records" edge of the Episode entity.
func (_m *Episode) QueryAnchoredDownloadRecords() *DownloadRecordQuery {
	return NewEpisodeClient(_m.config).QueryAnchoredDownloadRecords(_m)
}

// QueryMediaFiles queries the "media_files" edge of the Episode entity.
func (_m *Episode) QueryMediaFiles() *MediaFileQuery {
	return NewEpisodeClient(_m.config).QueryMediaFiles(_m)
}

// QueryEvents queries the "events" edge of the Episode entity.
func (_m *Episode) QueryEvents() *MediaEventQuery {
	return NewEpisodeClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Episode.
// Note that you need to call Episode.Unwrap() before calling this method if this Episode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Episode) Update() *EpisodeUpdateOne {
	return NewEpisodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Episode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Episode) Unwrap() *Episode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Episode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Episode) String() string {
	var builder strings.Builder
	builder.WriteString("Episode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", _m.Number))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("overview=")
	builder.WriteString(_m.Overview)
	builder.WriteString(", ")
	builder.WriteString("air_date=")
	builder.WriteString(_m.AirDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("monitored=")
	builder.WriteString(fmt.Sprintf("%v", _m.Monitored))
	builder.WriteString(", ")
	builder.WriteString("absolute_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.AbsoluteNumber))
	builder.WriteString(", ")
	builder.WriteString("grab_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrabFailures))
	builder.WriteString(", ")
	if v := _m.LastSearchAt; v != nil {
		builder.WriteString("last_search_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Episodes is a parsable slice of Episode.
type Episodes []*Episode
