// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/downloadrecord"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/mediaevent"
	"github.com/datahearth/streamline/ent/mediafile"
	"github.com/datahearth/streamline/ent/season"
)

// EpisodeCreate is the builder for creating a Episode entity.
type EpisodeCreate struct {
	config
	mutation *EpisodeMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *EpisodeCreate) SetCreateTime(v time.Time) *EpisodeCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableCreateTime(v *time.Time) *EpisodeCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *EpisodeCreate) SetUpdateTime(v time.Time) *EpisodeCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableUpdateTime(v *time.Time) *EpisodeCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetNumber sets the "number" field.
func (_c *EpisodeCreate) SetNumber(v uint16) *EpisodeCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *EpisodeCreate) SetTitle(v string) *EpisodeCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableTitle(v *string) *EpisodeCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetOverview sets the "overview" field.
func (_c *EpisodeCreate) SetOverview(v string) *EpisodeCreate {
	_c.mutation.SetOverview(v)
	return _c
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableOverview(v *string) *EpisodeCreate {
	if v != nil {
		_c.SetOverview(*v)
	}
	return _c
}

// SetAirDate sets the "air_date" field.
func (_c *EpisodeCreate) SetAirDate(v time.Time) *EpisodeCreate {
	_c.mutation.SetAirDate(v)
	return _c
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableAirDate(v *time.Time) *EpisodeCreate {
	if v != nil {
		_c.SetAirDate(*v)
	}
	return _c
}

// SetMonitored sets the "monitored" field.
func (_c *EpisodeCreate) SetMonitored(v bool) *EpisodeCreate {
	_c.mutation.SetMonitored(v)
	return _c
}

// SetNillableMonitored sets the "monitored" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableMonitored(v *bool) *EpisodeCreate {
	if v != nil {
		_c.SetMonitored(*v)
	}
	return _c
}

// SetAbsoluteNumber sets the "absolute_number" field.
func (_c *EpisodeCreate) SetAbsoluteNumber(v uint16) *EpisodeCreate {
	_c.mutation.SetAbsoluteNumber(v)
	return _c
}

// SetNillableAbsoluteNumber sets the "absolute_number" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableAbsoluteNumber(v *uint16) *EpisodeCreate {
	if v != nil {
		_c.SetAbsoluteNumber(*v)
	}
	return _c
}

// SetGrabFailures sets the "grab_failures" field.
func (_c *EpisodeCreate) SetGrabFailures(v uint8) *EpisodeCreate {
	_c.mutation.SetGrabFailures(v)
	return _c
}

// SetNillableGrabFailures sets the "grab_failures" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableGrabFailures(v *uint8) *EpisodeCreate {
	if v != nil {
		_c.SetGrabFailures(*v)
	}
	return _c
}

// SetLastSearchAt sets the "last_search_at" field.
func (_c *EpisodeCreate) SetLastSearchAt(v time.Time) *EpisodeCreate {
	_c.mutation.SetLastSearchAt(v)
	return _c
}

// SetNillableLastSearchAt sets the "last_search_at" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableLastSearchAt(v *time.Time) *EpisodeCreate {
	if v != nil {
		_c.SetLastSearchAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EpisodeCreate) SetStatus(v episode.Status) *EpisodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableStatus(v *episode.Status) *EpisodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EpisodeCreate) SetID(v uint32) *EpisodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSeasonID sets the "season" edge to the Season entity by ID.
func (_c *EpisodeCreate) SetSeasonID(id uint32) *EpisodeCreate {
	_c.mutation.SetSeasonID(id)
	return _c
}

// SetSeason sets the "season" edge to the Season entity.
func (_c *EpisodeCreate) SetSeason(v *Season) *EpisodeCreate {
	return _c.SetSeasonID(v.ID)
}

// AddDownloadRecordIDs adds the "download_records" edge to the DownloadRecord entity by IDs.
func (_c *EpisodeCreate) AddDownloadRecordIDs(ids ...uint32) *EpisodeCreate {
	_c.mutation.AddDownloadRecordIDs(ids...)
	return _c
}

// AddDownloadRecords adds the "download_records" edges to the DownloadRecord entity.
func (_c *EpisodeCreate) AddDownloadRecords(v ...*DownloadRecord) *EpisodeCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDownloadRecordIDs(ids...)
}

// AddAnchoredDownloadRecordIDs adds the "anchored_download_records" edge to the DownloadRecord entity by IDs.
func (_c *EpisodeCreate) AddAnchoredDownloadRecordIDs(ids ...uint32) *EpisodeCreate {
	_c.mutation.AddAnchoredDownloadRecordIDs(ids...)
	return _c
}

// AddAnchoredDownloadRecords adds the "anchored_download_records" edges to the DownloadRecord entity.
func (_c *EpisodeCreate) AddAnchoredDownloadRecords(v ...*DownloadRecord) *EpisodeCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnchoredDownloadRecordIDs(ids...)
}

// AddMediaFileIDs adds the "media_files" edge to the MediaFile entity by IDs.
func (_c *EpisodeCreate) AddMediaFileIDs(ids ...uint32) *EpisodeCreate {
	_c.mutation.AddMediaFileIDs(ids...)
	return _c
}

// AddMediaFiles adds the "media_files" edges to the MediaFile entity.
func (_c *EpisodeCreate) AddMediaFiles(v ...*MediaFile) *EpisodeCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMediaFileIDs(ids...)
}

// AddEventIDs adds the "events" edge to the MediaEvent entity by IDs.
func (_c *EpisodeCreate) AddEventIDs(ids ...uint32) *EpisodeCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the MediaEvent entity.
func (_c *EpisodeCreate) AddEvents(v ...*MediaEvent) *EpisodeCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_c *EpisodeCreate) Mutation() *EpisodeMutation {
	return _c.mutation
}

// Save creates the Episode in the database.
func (_c *EpisodeCreate) Save(ctx context.Context) (*Episode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EpisodeCreate) SaveX(ctx context.Context) *Episode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EpisodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EpisodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EpisodeCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := episode.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := episode.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Monitored(); !ok {
		v := episode.DefaultMonitored
		_c.mutation.SetMonitored(v)
	}
	if _, ok := _c.mutation.AbsoluteNumber(); !ok {
		v := episode.DefaultAbsoluteNumber
		_c.mutation.SetAbsoluteNumber(v)
	}
	if _, ok := _c.mutation.GrabFailures(); !ok {
		v := episode.DefaultGrabFailures
		_c.mutation.SetGrabFailures(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := episode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EpisodeCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Episode.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Episode.update_time"`)}
	}
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Episode.number"`)}
	}
	if _, ok := _c.mutation.Monitored(); !ok {
		return &ValidationError{Name: "monitored", err: errors.New(`ent: missing required field "Episode.monitored"`)}
	}
	if _, ok := _c.mutation.GrabFailures(); !ok {
		return &ValidationError{Name: "grab_failures", err: errors.New(`ent: missing required field "Episode.grab_failures"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Episode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := episode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Episode.status": %w`, err)}
		}
	}
	if len(_c.mutation.SeasonIDs()) == 0 {
		return &ValidationError{Name: "season", err: errors.New(`ent: missing required edge "Episode.season"`)}
	}
	return nil
}

func (_c *EpisodeCreate) sqlSave(ctx context.Context) (*Episode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EpisodeCreate) createSpec() (*Episode, *sqlgraph.CreateSpec) {
	var (
		_node = &Episode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(episode.Table, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(episode.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(episode.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(episode.FieldNumber, field.TypeUint16, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Overview(); ok {
		_spec.SetField(episode.FieldOverview, field.TypeString, value)
		_node.Overview = value
	}
	if value, ok := _c.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
		_node.AirDate = value
	}
	if value, ok := _c.mutation.Monitored(); ok {
		_spec.SetField(episode.FieldMonitored, field.TypeBool, value)
		_node.Monitored = value
	}
	if value, ok := _c.mutation.AbsoluteNumber(); ok {
		_spec.SetField(episode.FieldAbsoluteNumber, field.TypeUint16, value)
		_node.AbsoluteNumber = value
	}
	if value, ok := _c.mutation.GrabFailures(); ok {
		_spec.SetField(episode.FieldGrabFailures, field.TypeUint8, value)
		_node.GrabFailures = value
	}
	if value, ok := _c.mutation.LastSearchAt(); ok {
		_spec.SetField(episode.FieldLastSearchAt, field.TypeTime, value)
		_node.LastSearchAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(episode.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.season_episodes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DownloadRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnchoredDownloadRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MediaFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EpisodeCreateBulk is the builder for creating many Episode entities in bulk.
type EpisodeCreateBulk struct {
	config
	err      error
	builders []*EpisodeCreate
}

// Save creates the Episode entities in the database.
func (_c *EpisodeCreateBulk) Save(ctx context.Context) ([]*Episode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Episode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EpisodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EpisodeCreateBulk) SaveX(ctx context.Context) []*Episode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EpisodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EpisodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
