// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/downloadrecord"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/mediaevent"
	"github.com/datahearth/streamline/ent/mediafile"
	"github.com/datahearth/streamline/ent/predicate"
	"github.com/datahearth/streamline/ent/season"
)

// EpisodeUpdate is the builder for updating Episode entities.
type EpisodeUpdate struct {
	config
	hooks     []Hook
	mutation  *EpisodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (_u *EpisodeUpdate) Where(ps ...predicate.Episode) *EpisodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *EpisodeUpdate) SetUpdateTime(v time.Time) *EpisodeUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNumber sets the "number" field.
func (_u *EpisodeUpdate) SetNumber(v uint16) *EpisodeUpdate {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableNumber(v *uint16) *EpisodeUpdate {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *EpisodeUpdate) AddNumber(v int16) *EpisodeUpdate {
	_u.mutation.AddNumber(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *EpisodeUpdate) SetTitle(v string) *EpisodeUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableTitle(v *string) *EpisodeUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *EpisodeUpdate) ClearTitle() *EpisodeUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *EpisodeUpdate) SetOverview(v string) *EpisodeUpdate {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableOverview(v *string) *EpisodeUpdate {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// ClearOverview clears the value of the "overview" field.
func (_u *EpisodeUpdate) ClearOverview() *EpisodeUpdate {
	_u.mutation.ClearOverview()
	return _u
}

// SetAirDate sets the "air_date" field.
func (_u *EpisodeUpdate) SetAirDate(v time.Time) *EpisodeUpdate {
	_u.mutation.SetAirDate(v)
	return _u
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableAirDate(v *time.Time) *EpisodeUpdate {
	if v != nil {
		_u.SetAirDate(*v)
	}
	return _u
}

// ClearAirDate clears the value of the "air_date" field.
func (_u *EpisodeUpdate) ClearAirDate() *EpisodeUpdate {
	_u.mutation.ClearAirDate()
	return _u
}

// SetMonitored sets the "monitored" field.
func (_u *EpisodeUpdate) SetMonitored(v bool) *EpisodeUpdate {
	_u.mutation.SetMonitored(v)
	return _u
}

// SetNillableMonitored sets the "monitored" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableMonitored(v *bool) *EpisodeUpdate {
	if v != nil {
		_u.SetMonitored(*v)
	}
	return _u
}

// SetAbsoluteNumber sets the "absolute_number" field.
func (_u *EpisodeUpdate) SetAbsoluteNumber(v uint16) *EpisodeUpdate {
	_u.mutation.ResetAbsoluteNumber()
	_u.mutation.SetAbsoluteNumber(v)
	return _u
}

// SetNillableAbsoluteNumber sets the "absolute_number" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableAbsoluteNumber(v *uint16) *EpisodeUpdate {
	if v != nil {
		_u.SetAbsoluteNumber(*v)
	}
	return _u
}

// AddAbsoluteNumber adds value to the "absolute_number" field.
func (_u *EpisodeUpdate) AddAbsoluteNumber(v int16) *EpisodeUpdate {
	_u.mutation.AddAbsoluteNumber(v)
	return _u
}

// ClearAbsoluteNumber clears the value of the "absolute_number" field.
func (_u *EpisodeUpdate) ClearAbsoluteNumber() *EpisodeUpdate {
	_u.mutation.ClearAbsoluteNumber()
	return _u
}

// SetGrabFailures sets the "grab_failures" field.
func (_u *EpisodeUpdate) SetGrabFailures(v uint8) *EpisodeUpdate {
	_u.mutation.ResetGrabFailures()
	_u.mutation.SetGrabFailures(v)
	return _u
}

// SetNillableGrabFailures sets the "grab_failures" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableGrabFailures(v *uint8) *EpisodeUpdate {
	if v != nil {
		_u.SetGrabFailures(*v)
	}
	return _u
}

// AddGrabFailures adds value to the "grab_failures" field.
func (_u *EpisodeUpdate) AddGrabFailures(v int8) *EpisodeUpdate {
	_u.mutation.AddGrabFailures(v)
	return _u
}

// SetLastSearchAt sets the "last_search_at" field.
func (_u *EpisodeUpdate) SetLastSearchAt(v time.Time) *EpisodeUpdate {
	_u.mutation.SetLastSearchAt(v)
	return _u
}

// SetNillableLastSearchAt sets the "last_search_at" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableLastSearchAt(v *time.Time) *EpisodeUpdate {
	if v != nil {
		_u.SetLastSearchAt(*v)
	}
	return _u
}

// ClearLastSearchAt clears the value of the "last_search_at" field.
func (_u *EpisodeUpdate) ClearLastSearchAt() *EpisodeUpdate {
	_u.mutation.ClearLastSearchAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EpisodeUpdate) SetStatus(v episode.Status) *EpisodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableStatus(v *episode.Status) *EpisodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeasonID sets the "season" edge to the Season entity by ID.
func (_u *EpisodeUpdate) SetSeasonID(id uint32) *EpisodeUpdate {
	_u.mutation.SetSeasonID(id)
	return _u
}

// SetSeason sets the "season" edge to the Season entity.
func (_u *EpisodeUpdate) SetSeason(v *Season) *EpisodeUpdate {
	return _u.SetSeasonID(v.ID)
}

// AddDownloadRecordIDs adds the "download_records" edge to the DownloadRecord entity by IDs.
func (_u *EpisodeUpdate) AddDownloadRecordIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.AddDownloadRecordIDs(ids...)
	return _u
}

// AddDownloadRecords adds the "download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdate) AddDownloadRecords(v ...*DownloadRecord) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDownloadRecordIDs(ids...)
}

// AddAnchoredDownloadRecordIDs adds the "anchored_download_records" edge to the DownloadRecord entity by IDs.
func (_u *EpisodeUpdate) AddAnchoredDownloadRecordIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.AddAnchoredDownloadRecordIDs(ids...)
	return _u
}

// AddAnchoredDownloadRecords adds the "anchored_download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdate) AddAnchoredDownloadRecords(v ...*DownloadRecord) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnchoredDownloadRecordIDs(ids...)
}

// AddMediaFileIDs adds the "media_files" edge to the MediaFile entity by IDs.
func (_u *EpisodeUpdate) AddMediaFileIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.AddMediaFileIDs(ids...)
	return _u
}

// AddMediaFiles adds the "media_files" edges to the MediaFile entity.
func (_u *EpisodeUpdate) AddMediaFiles(v ...*MediaFile) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMediaFileIDs(ids...)
}

// AddEventIDs adds the "events" edge to the MediaEvent entity by IDs.
func (_u *EpisodeUpdate) AddEventIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the MediaEvent entity.
func (_u *EpisodeUpdate) AddEvents(v ...*MediaEvent) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_u *EpisodeUpdate) Mutation() *EpisodeMutation {
	return _u.mutation
}

// ClearSeason clears the "season" edge to the Season entity.
func (_u *EpisodeUpdate) ClearSeason() *EpisodeUpdate {
	_u.mutation.ClearSeason()
	return _u
}

// ClearDownloadRecords clears all "download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdate) ClearDownloadRecords() *EpisodeUpdate {
	_u.mutation.ClearDownloadRecords()
	return _u
}

// RemoveDownloadRecordIDs removes the "download_records" edge to DownloadRecord entities by IDs.
func (_u *EpisodeUpdate) RemoveDownloadRecordIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.RemoveDownloadRecordIDs(ids...)
	return _u
}

// RemoveDownloadRecords removes "download_records" edges to DownloadRecord entities.
func (_u *EpisodeUpdate) RemoveDownloadRecords(v ...*DownloadRecord) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDownloadRecordIDs(ids...)
}

// ClearAnchoredDownloadRecords clears all "anchored_download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdate) ClearAnchoredDownloadRecords() *EpisodeUpdate {
	_u.mutation.ClearAnchoredDownloadRecords()
	return _u
}

// RemoveAnchoredDownloadRecordIDs removes the "anchored_download_records" edge to DownloadRecord entities by IDs.
func (_u *EpisodeUpdate) RemoveAnchoredDownloadRecordIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.RemoveAnchoredDownloadRecordIDs(ids...)
	return _u
}

// RemoveAnchoredDownloadRecords removes "anchored_download_records" edges to DownloadRecord entities.
func (_u *EpisodeUpdate) RemoveAnchoredDownloadRecords(v ...*DownloadRecord) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnchoredDownloadRecordIDs(ids...)
}

// ClearMediaFiles clears all "media_files" edges to the MediaFile entity.
func (_u *EpisodeUpdate) ClearMediaFiles() *EpisodeUpdate {
	_u.mutation.ClearMediaFiles()
	return _u
}

// RemoveMediaFileIDs removes the "media_files" edge to MediaFile entities by IDs.
func (_u *EpisodeUpdate) RemoveMediaFileIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.RemoveMediaFileIDs(ids...)
	return _u
}

// RemoveMediaFiles removes "media_files" edges to MediaFile entities.
func (_u *EpisodeUpdate) RemoveMediaFiles(v ...*MediaFile) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMediaFileIDs(ids...)
}

// ClearEvents clears all "events" edges to the MediaEvent entity.
func (_u *EpisodeUpdate) ClearEvents() *EpisodeUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to MediaEvent entities by IDs.
func (_u *EpisodeUpdate) RemoveEventIDs(ids ...uint32) *EpisodeUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to MediaEvent entities.
func (_u *EpisodeUpdate) RemoveEvents(v ...*MediaEvent) *EpisodeUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EpisodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EpisodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EpisodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EpisodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EpisodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := episode.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EpisodeUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := episode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Episode.status": %w`, err)}
		}
	}
	if _u.mutation.SeasonCleared() && len(_u.mutation.SeasonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Episode.season"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EpisodeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EpisodeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EpisodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(episode.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(episode.FieldNumber, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(episode.FieldNumber, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(episode.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(episode.FieldOverview, field.TypeString, value)
	}
	if _u.mutation.OverviewCleared() {
		_spec.ClearField(episode.FieldOverview, field.TypeString)
	}
	if value, ok := _u.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
	}
	if _u.mutation.AirDateCleared() {
		_spec.ClearField(episode.FieldAirDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Monitored(); ok {
		_spec.SetField(episode.FieldMonitored, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AbsoluteNumber(); ok {
		_spec.SetField(episode.FieldAbsoluteNumber, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedAbsoluteNumber(); ok {
		_spec.AddField(episode.FieldAbsoluteNumber, field.TypeUint16, value)
	}
	if _u.mutation.AbsoluteNumberCleared() {
		_spec.ClearField(episode.FieldAbsoluteNumber, field.TypeUint16)
	}
	if value, ok := _u.mutation.GrabFailures(); ok {
		_spec.SetField(episode.FieldGrabFailures, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedGrabFailures(); ok {
		_spec.AddField(episode.FieldGrabFailures, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.LastSearchAt(); ok {
		_spec.SetField(episode.FieldLastSearchAt, field.TypeTime, value)
	}
	if _u.mutation.LastSearchAtCleared() {
		_spec.ClearField(episode.FieldLastSearchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(episode.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.SeasonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDownloadRecordsIDs(); len(nodes) > 0 && !_u.mutation.DownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DownloadRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnchoredDownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnchoredDownloadRecordsIDs(); len(nodes) > 0 && !_u.mutation.AnchoredDownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnchoredDownloadRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MediaFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMediaFilesIDs(); len(nodes) > 0 && !_u.mutation.MediaFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EpisodeUpdateOne is the builder for updating a single Episode entity.
type EpisodeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EpisodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *EpisodeUpdateOne) SetUpdateTime(v time.Time) *EpisodeUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNumber sets the "number" field.
func (_u *EpisodeUpdateOne) SetNumber(v uint16) *EpisodeUpdateOne {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableNumber(v *uint16) *EpisodeUpdateOne {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *EpisodeUpdateOne) AddNumber(v int16) *EpisodeUpdateOne {
	_u.mutation.AddNumber(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *EpisodeUpdateOne) SetTitle(v string) *EpisodeUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableTitle(v *string) *EpisodeUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *EpisodeUpdateOne) ClearTitle() *EpisodeUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *EpisodeUpdateOne) SetOverview(v string) *EpisodeUpdateOne {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableOverview(v *string) *EpisodeUpdateOne {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// ClearOverview clears the value of the "overview" field.
func (_u *EpisodeUpdateOne) ClearOverview() *EpisodeUpdateOne {
	_u.mutation.ClearOverview()
	return _u
}

// SetAirDate sets the "air_date" field.
func (_u *EpisodeUpdateOne) SetAirDate(v time.Time) *EpisodeUpdateOne {
	_u.mutation.SetAirDate(v)
	return _u
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableAirDate(v *time.Time) *EpisodeUpdateOne {
	if v != nil {
		_u.SetAirDate(*v)
	}
	return _u
}

// ClearAirDate clears the value of the "air_date" field.
func (_u *EpisodeUpdateOne) ClearAirDate() *EpisodeUpdateOne {
	_u.mutation.ClearAirDate()
	return _u
}

// SetMonitored sets the "monitored" field.
func (_u *EpisodeUpdateOne) SetMonitored(v bool) *EpisodeUpdateOne {
	_u.mutation.SetMonitored(v)
	return _u
}

// SetNillableMonitored sets the "monitored" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableMonitored(v *bool) *EpisodeUpdateOne {
	if v != nil {
		_u.SetMonitored(*v)
	}
	return _u
}

// SetAbsoluteNumber sets the "absolute_number" field.
func (_u *EpisodeUpdateOne) SetAbsoluteNumber(v uint16) *EpisodeUpdateOne {
	_u.mutation.ResetAbsoluteNumber()
	_u.mutation.SetAbsoluteNumber(v)
	return _u
}

// SetNillableAbsoluteNumber sets the "absolute_number" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableAbsoluteNumber(v *uint16) *EpisodeUpdateOne {
	if v != nil {
		_u.SetAbsoluteNumber(*v)
	}
	return _u
}

// AddAbsoluteNumber adds value to the "absolute_number" field.
func (_u *EpisodeUpdateOne) AddAbsoluteNumber(v int16) *EpisodeUpdateOne {
	_u.mutation.AddAbsoluteNumber(v)
	return _u
}

// ClearAbsoluteNumber clears the value of the "absolute_number" field.
func (_u *EpisodeUpdateOne) ClearAbsoluteNumber() *EpisodeUpdateOne {
	_u.mutation.ClearAbsoluteNumber()
	return _u
}

// SetGrabFailures sets the "grab_failures" field.
func (_u *EpisodeUpdateOne) SetGrabFailures(v uint8) *EpisodeUpdateOne {
	_u.mutation.ResetGrabFailures()
	_u.mutation.SetGrabFailures(v)
	return _u
}

// SetNillableGrabFailures sets the "grab_failures" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableGrabFailures(v *uint8) *EpisodeUpdateOne {
	if v != nil {
		_u.SetGrabFailures(*v)
	}
	return _u
}

// AddGrabFailures adds value to the "grab_failures" field.
func (_u *EpisodeUpdateOne) AddGrabFailures(v int8) *EpisodeUpdateOne {
	_u.mutation.AddGrabFailures(v)
	return _u
}

// SetLastSearchAt sets the "last_search_at" field.
func (_u *EpisodeUpdateOne) SetLastSearchAt(v time.Time) *EpisodeUpdateOne {
	_u.mutation.SetLastSearchAt(v)
	return _u
}

// SetNillableLastSearchAt sets the "last_search_at" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableLastSearchAt(v *time.Time) *EpisodeUpdateOne {
	if v != nil {
		_u.SetLastSearchAt(*v)
	}
	return _u
}

// ClearLastSearchAt clears the value of the "last_search_at" field.
func (_u *EpisodeUpdateOne) ClearLastSearchAt() *EpisodeUpdateOne {
	_u.mutation.ClearLastSearchAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EpisodeUpdateOne) SetStatus(v episode.Status) *EpisodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableStatus(v *episode.Status) *EpisodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeasonID sets the "season" edge to the Season entity by ID.
func (_u *EpisodeUpdateOne) SetSeasonID(id uint32) *EpisodeUpdateOne {
	_u.mutation.SetSeasonID(id)
	return _u
}

// SetSeason sets the "season" edge to the Season entity.
func (_u *EpisodeUpdateOne) SetSeason(v *Season) *EpisodeUpdateOne {
	return _u.SetSeasonID(v.ID)
}

// AddDownloadRecordIDs adds the "download_records" edge to the DownloadRecord entity by IDs.
func (_u *EpisodeUpdateOne) AddDownloadRecordIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.AddDownloadRecordIDs(ids...)
	return _u
}

// AddDownloadRecords adds the "download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdateOne) AddDownloadRecords(v ...*DownloadRecord) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDownloadRecordIDs(ids...)
}

// AddAnchoredDownloadRecordIDs adds the "anchored_download_records" edge to the DownloadRecord entity by IDs.
func (_u *EpisodeUpdateOne) AddAnchoredDownloadRecordIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.AddAnchoredDownloadRecordIDs(ids...)
	return _u
}

// AddAnchoredDownloadRecords adds the "anchored_download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdateOne) AddAnchoredDownloadRecords(v ...*DownloadRecord) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnchoredDownloadRecordIDs(ids...)
}

// AddMediaFileIDs adds the "media_files" edge to the MediaFile entity by IDs.
func (_u *EpisodeUpdateOne) AddMediaFileIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.AddMediaFileIDs(ids...)
	return _u
}

// AddMediaFiles adds the "media_files" edges to the MediaFile entity.
func (_u *EpisodeUpdateOne) AddMediaFiles(v ...*MediaFile) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMediaFileIDs(ids...)
}

// AddEventIDs adds the "events" edge to the MediaEvent entity by IDs.
func (_u *EpisodeUpdateOne) AddEventIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the MediaEvent entity.
func (_u *EpisodeUpdateOne) AddEvents(v ...*MediaEvent) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_u *EpisodeUpdateOne) Mutation() *EpisodeMutation {
	return _u.mutation
}

// ClearSeason clears the "season" edge to the Season entity.
func (_u *EpisodeUpdateOne) ClearSeason() *EpisodeUpdateOne {
	_u.mutation.ClearSeason()
	return _u
}

// ClearDownloadRecords clears all "download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdateOne) ClearDownloadRecords() *EpisodeUpdateOne {
	_u.mutation.ClearDownloadRecords()
	return _u
}

// RemoveDownloadRecordIDs removes the "download_records" edge to DownloadRecord entities by IDs.
func (_u *EpisodeUpdateOne) RemoveDownloadRecordIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.RemoveDownloadRecordIDs(ids...)
	return _u
}

// RemoveDownloadRecords removes "download_records" edges to DownloadRecord entities.
func (_u *EpisodeUpdateOne) RemoveDownloadRecords(v ...*DownloadRecord) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDownloadRecordIDs(ids...)
}

// ClearAnchoredDownloadRecords clears all "anchored_download_records" edges to the DownloadRecord entity.
func (_u *EpisodeUpdateOne) ClearAnchoredDownloadRecords() *EpisodeUpdateOne {
	_u.mutation.ClearAnchoredDownloadRecords()
	return _u
}

// RemoveAnchoredDownloadRecordIDs removes the "anchored_download_records" edge to DownloadRecord entities by IDs.
func (_u *EpisodeUpdateOne) RemoveAnchoredDownloadRecordIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.RemoveAnchoredDownloadRecordIDs(ids...)
	return _u
}

// RemoveAnchoredDownloadRecords removes "anchored_download_records" edges to DownloadRecord entities.
func (_u *EpisodeUpdateOne) RemoveAnchoredDownloadRecords(v ...*DownloadRecord) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnchoredDownloadRecordIDs(ids...)
}

// ClearMediaFiles clears all "media_files" edges to the MediaFile entity.
func (_u *EpisodeUpdateOne) ClearMediaFiles() *EpisodeUpdateOne {
	_u.mutation.ClearMediaFiles()
	return _u
}

// RemoveMediaFileIDs removes the "media_files" edge to MediaFile entities by IDs.
func (_u *EpisodeUpdateOne) RemoveMediaFileIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.RemoveMediaFileIDs(ids...)
	return _u
}

// RemoveMediaFiles removes "media_files" edges to MediaFile entities.
func (_u *EpisodeUpdateOne) RemoveMediaFiles(v ...*MediaFile) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMediaFileIDs(ids...)
}

// ClearEvents clears all "events" edges to the MediaEvent entity.
func (_u *EpisodeUpdateOne) ClearEvents() *EpisodeUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to MediaEvent entities by IDs.
func (_u *EpisodeUpdateOne) RemoveEventIDs(ids ...uint32) *EpisodeUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to MediaEvent entities.
func (_u *EpisodeUpdateOne) RemoveEvents(v ...*MediaEvent) *EpisodeUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (_u *EpisodeUpdateOne) Where(ps ...predicate.Episode) *EpisodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EpisodeUpdateOne) Select(field string, fields ...string) *EpisodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Episode entity.
func (_u *EpisodeUpdateOne) Save(ctx context.Context) (*Episode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EpisodeUpdateOne) SaveX(ctx context.Context) *Episode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EpisodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EpisodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EpisodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := episode.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EpisodeUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := episode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Episode.status": %w`, err)}
		}
	}
	if _u.mutation.SeasonCleared() && len(_u.mutation.SeasonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Episode.season"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EpisodeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EpisodeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EpisodeUpdateOne) sqlSave(ctx context.Context) (_node *Episode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Episode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, episode.FieldID)
		for _, f := range fields {
			if !episode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != episode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(episode.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(episode.FieldNumber, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(episode.FieldNumber, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(episode.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(episode.FieldOverview, field.TypeString, value)
	}
	if _u.mutation.OverviewCleared() {
		_spec.ClearField(episode.FieldOverview, field.TypeString)
	}
	if value, ok := _u.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
	}
	if _u.mutation.AirDateCleared() {
		_spec.ClearField(episode.FieldAirDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Monitored(); ok {
		_spec.SetField(episode.FieldMonitored, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AbsoluteNumber(); ok {
		_spec.SetField(episode.FieldAbsoluteNumber, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedAbsoluteNumber(); ok {
		_spec.AddField(episode.FieldAbsoluteNumber, field.TypeUint16, value)
	}
	if _u.mutation.AbsoluteNumberCleared() {
		_spec.ClearField(episode.FieldAbsoluteNumber, field.TypeUint16)
	}
	if value, ok := _u.mutation.GrabFailures(); ok {
		_spec.SetField(episode.FieldGrabFailures, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedGrabFailures(); ok {
		_spec.AddField(episode.FieldGrabFailures, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.LastSearchAt(); ok {
		_spec.SetField(episode.FieldLastSearchAt, field.TypeTime, value)
	}
	if _u.mutation.LastSearchAtCleared() {
		_spec.ClearField(episode.FieldLastSearchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(episode.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.SeasonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDownloadRecordsIDs(); len(nodes) > 0 && !_u.mutation.DownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DownloadRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   episode.DownloadRecordsTable,
			Columns: episode.DownloadRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnchoredDownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnchoredDownloadRecordsIDs(); len(nodes) > 0 && !_u.mutation.AnchoredDownloadRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnchoredDownloadRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.AnchoredDownloadRecordsTable,
			Columns: []string{episode.AnchoredDownloadRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MediaFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMediaFilesIDs(); len(nodes) > 0 && !_u.mutation.MediaFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.MediaFilesTable,
			Columns: []string{episode.MediaFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   episode.EventsTable,
			Columns: []string{episode.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Episode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
